
@startuml
class "epo-ord:AllowanceChargeInformation" {
  epo-cat:hasAmount : epo:MonetaryValue [1]
  epo-cat:hasPercentage : xsd:decimal [0..1]
  epo-ful:hasAllowanceChargeReason : at-voc-new:allowance-charge-reason [0..1]
  epo-ful:hasAllowanceChargeReasonDescription : rdf:PlainLiteral [0..*]
  epo-ord:hasTaxInformation : epo-ord:TaxInformation [0..1]
  epo:isCalculatedOn : epo:MonetaryValue [0..1]
}

class "epo-ord:AllowanceInformation" {
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}

class "epo-ord:Consignee" {

}

class "epo-ord:ContractInformation" {
  epo-ord:concernsContract : epo:Contract [1]
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}

class "epo-ord:DeliveryAgreement" {
  dct:description : rdf:PlainLiteral [0..*]
  epo-ord:specifiesDeliveryAgreementLocation : dct:Location [0..1]
}

class "epo-ord:DeliveryInformation" {
  epo-ful:hasTrackingID : adms:Identifier [0..1]
  epo-ord:concernsConsignee : epo-ord:Consignee [0..1]
  epo-ord:hasDeliveryDeadline : xsd:dateTime [0..1]
  epo-ord:hasDeliveryPeriod : epo:Period [0..1]
  epo-ord:hasShippingMark : rdf:PlainLiteral [0..*]
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
  epo-ord:specifiesGeneralDeliveryAgreement : epo-ord:DeliveryAgreement [0..1]
  epo-ord:specifiesPlaceOfDelivery : dct:Location [0..1]
  epo-ord:specifiesSpecificDeliveryAgreement : epo-ord:DeliveryAgreement [0..1]
}

class "epo-ord:Order" {
  epo-cat:specifiesChargeInformation : epo-cat:ChargeInformation [0..*]
  epo-ord:comprisesOrderLine : epo-ord:OrderLine [1..*]
  epo-ord:hasAccountingCost : rdf:PlainLiteral [0..1]
  epo-ord:hasAmountDueForPayment : epo:MonetaryValue [1]
  epo-ord:hasCustomerReference : xsd:boolean [0..1]
  epo-ord:hasPaymentTerm : rdf:PlainLiteral [0..1]
  epo-ord:hasPrepaidAmount : epo:MonetaryValue [0..1]
  epo-ord:hasRoundingAmount : epo:MonetaryValue [0..1]
  epo-ord:hasTotalAllowanceAmount : epo:MonetaryValue [0..1]
  epo-ord:hasTotalChargeAmount : epo:MonetaryValue [0..1]
  epo-ord:hasTotalLineAmount : epo:MonetaryValue [1]
  epo-ord:hasTotalTaxExclusiveAmount : epo:MonetaryValue [0..1]
  epo-ord:hasTotalTaxInclusiveAmount : epo:MonetaryValue [0..1]
  epo-ord:refersToCatalogue : epo-cat:Catalogue [0..*]
  epo-ord:specifiesAllowanceInformation : epo-ord:AllowanceInformation [0..*]
  epo-ord:specifiesContractInformation : epo-ord:ContractInformation [0..*]
  epo-ord:specifiesDeliveryInformation : epo-ord:DeliveryInformation [1..*]
  epo-ord:specifiesOriginatorInformation : epo-ord:OriginatorInformation [0..1]
  epo:refersToProject : epo:Project [0..1]
  epo:specifiesBuyer : epo:Buyer [1]
  epo:specifiesDespatcher : epo-ful:Despatcher [0..1]
  epo:specifiesSeller : epo-ord:Seller [1]
}

class "epo-ord:OrderLine" {
  epo-cat:hasPrice : epo-cat:Price [0..1]
  epo-cat:hasQuantity : epo:Quantity [1]
  epo-ord:refersToCatalogueLine : epo-cat:CatalogueLine [0..1]
}

class "epo-ord:OrderResponse" {
  epo-ord:comprisesOrderResponseLine : epo-ord:OrderResponseLine [0..*]
  epo-ord:hasResponseDescription : rdf:PlainLiteral [0..1]
  epo-ord:implementsContract : epo:Contract [0..1]
  epo-ord:isSubmittedForOrder : epo-ord:Order [1]
  epo-ord:specifiesBuyer : epo:Buyer [0..1]
  epo-ord:specifiesOrderResponseInformation : epo-ord:OrderResponseInformation [0..*]
  epo-ord:specifiesSeller : epo-ord:Seller [0..1]
}

class "epo-ord:OrderResponseInformation" {
  epo-ord:hasAcceptanceStatus : at-voc-new:ResponseStatus [1]
  epo-ord:hasDeliveryPeriod : epo:Period [0..1]
  epo-ord:isSpecificToOrderResponseLine : epo-ord:OrderResponseLine [0..*]
}

class "epo-ord:OrderResponseLine" {
  epo-ord:isSubmittedForOrderLine : epo-ord:OrderLine [1..*]
}

class "epo-ord:Originator" {

}

class "epo-ord:OriginatorInformation" {
  epo-ord:concernsOriginator : epo-ord:Originator [1]
  epo-ord:concernsOriginatorRequest : epo:OriginatorRequest [0..1]
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}

class "epo-ord:Seller" {

}

class "epo-ord:TaxInformation" {
  dct:description : rdf:PlainLiteral [0..1]
  epo-cat:hasAmount : epo:MonetaryValue [0..1]
  epo-cat:hasPercentage : xsd:decimal [0..1]
  epo-cat:hasTaxCategory : at-voc-new:tax-category [0..1]
  epo-cat:hasTaxScheme : at-voc-new:tax-scheme [0..1]
  epo:isCalculatedOn : epo:MonetaryValue [0..1]
}

@enduml
