
@startuml
class "epo-cat:Batch" {
  epo-cat:hasBestBeforeDate : xsd:date [0..1]
  epo-cat:hasExpiryDate : xsd:date [0..1]
  epo-cat:isProductionOf : epo-cat:Item [1]
  epo:hasID : epo:Identifier [0..1]
}

class "epo-cat:Brand" {
  epo:hasName : rdfs:Literal [1..1]
}

class "epo-cat:Catalogue" {
  epo-cat:comprisesCatalogueLine : epo-cat:CatalogueLine [1..*]
  epo-cat:hasSpecificPaymentArrangement : rdfs:Literal [0..1]
  epo-cat:isProvidedByCatalogueProvider : epo:CatalogueProvider [0..1]
  epo-cat:isSubordinatedToContract : epo:Contract [0..1]
  epo:hasValidityPeriod : epo:Period [0..1]
}

class "epo-cat:CatalogueDocument" {
  epo-cat:instantiatesCatalogue : epo-cat:Catalogue [0..1]
  epo:hasName : rdfs:Literal [1..1]
}

class "epo-cat:CatalogueFragment" {
  epo-cat:hasActivityCode : epo-cat:activity-code [0..1]
  epo-cat:updatesCatalogue : epo-cat:Catalogue [1]
}

class "epo-cat:CatalogueLine" {
  epo-cat:hasCatalogueLineValidity : epo:Period [0..1]
  epo-cat:hasChargeInformation : epo-cat:ChargeInformation [0..*]
  epo-cat:hasMaximumOrderQuantity : epo:Quantity [0..1]
  epo-cat:hasMinimumQuantityGuaranteedForDelivery : epo:Quantity [0..1]
  epo-cat:hasOrderableQuantityIncrement : xsd:integer [0..1]
  epo-cat:hasOrderableUnit : epo-cat:orderable-unit [0..1]
  epo-cat:hasOrderableUnitFactorRate : xsd:decimal [0..1]
  epo-cat:hasPrice : epo-cat:Price [1..*]
  epo-cat:hasStandardisedUnitPrice : epo-cat:Price [0..*]
  epo-cat:hasTransactionConditions : rdfs:Literal [0..1]
  epo-cat:hasTransactionConditionsCode : epo-cat:transaction-conditions [0..1]
  epo-cat:hasWarrantyInformation : rdfs:Literal [0..1]
  epo-cat:isContractedItem : xsd:boolean [0..1]
  epo-cat:isOrderable : xsd:boolean [0..1]
  epo-cat:specifiesItem : epo-cat:Item [1]
  epo:hasID : epo:Identifier [1]
}

class "epo-cat:CatalogueUpdateDocument" {
  epo-cat:announcesCatalogueFragment : epo-cat:CatalogueFragment [0..*]
  epo-cat:hasSourceCatalogueVersion : rdfs:Literal [1..1]
  epo-cat:hasTargetCatalogueVersion : rdfs:Literal [1..1]
}

class "epo-cat:CertificationLabel" {
  epo-cat:hasLabelType : at-voc-new:certification-label-type [0..1]
  epo-cat:hasReferenceURI : xsd:anyURI [0..1]
}

class "epo-cat:Certifier" {

}

class "epo-cat:ChargeInformation" {
  epo-cat:hasChargeCategory : at-voc-new:charge-category [1]
  epo-cat:hasChargeCategoryModifier : at-voc-new:charge-modifier [0..1]
}

class "epo-cat:Item" {
  dct:hasPart : epo-cat:Item [0..*]
  dct:isReplaceBy : epo-cat:Item [0..*]
  dct:requires : epo-cat:Item [0..*]
  epo-cat:hasAccessoryItem : epo-cat:Item [0..*]
  epo-cat:hasBrand : epo-cat:Brand [0..1]
  epo-cat:hasCertification : epo-cat:ItemCertificate [0..*]
  epo-cat:hasComplementaryItem : epo-cat:Item [0..*]
  epo-cat:hasCountryOfOrigin : at-voc:country [0..1]
  epo-cat:hasDeliveryClassification : at-voc-new:delivery-item-type [0..1]
  epo-cat:hasDimensionDescription : rdfs:Literal [0..*]
  epo-cat:hasExternalSpecification : xsd:anyURI [0..*]
  epo-cat:hasHazardousClass : rdfs:Literal [0..1]
  epo-cat:hasHazardousItemUNDGCode : at-voc-new:dangerous-goods-list [0..1]
  epo-cat:hasItemClassification : at-voc-new:unspc [0..*]
  epo-cat:hasKeyword : rdfs:Literal [0..*]
  epo-cat:hasManufacturer : epo-cat:Manufacturer [0..1]
  epo-cat:hasModel : epo-cat:ItemModel [0..1]
  epo-cat:hasNetQuantity : epo:Quantity [0..1]
  epo-cat:hasQualifiedItemRelation : epo-cat:ItemRelation [0..*]
  epo-cat:hasSpecification : epo-cat:ProductSpecification [0..*]
  epo-cat:hasVATCategoryCode : epo-cat:vat-category [0..1]
  epo-cat:hasVATRate : xsd:decimal [0..1]
  epo-cat:isInStock : xsd:boolean [0..1]
  epo:hasCatalogueItemID : epo:Identifier [0..1]
  epo:hasDescription : rdfs:Literal [0..1]
  epo:hasItemStandardID : epo:Identifier [0..1]
  epo:hasManufacturerItemID : epo:Identifier [0..1]
  epo:hasName : rdfs:Literal [1..1]
}

class "epo-cat:ItemAccessoryRelation" {

}

class "epo-cat:ItemCertificate" {
  epo-cat:attestedByLabel : epo-cat:CertificationLabel [1]
  epo-cat:hasCertificationNumber : rdfs:Literal [1..1]
  epo-cat:issuedByCertifier : epo-cat:Certifier [0..1]
  epo:hasURL : xsd:anyURI [0..1]
  epo:hasValidityPeriod : epo:Period [0..1]
}

class "epo-cat:ItemComplementaryRelation" {

}

class "epo-cat:ItemComposition" {

}

class "epo-cat:ItemDescription" {
  epo-cat:describesItem : epo-cat:Item [1]
  epo-cat:hasAttributeType : rdfs:Literal [1..1]
  epo-cat:hasClassificationScheme : rdfs:Literal [1..1]
  epo-cat:hasLiteralValue : rdfs:Literal [0..1]
  epo-cat:hasQualifiedValue : epo:Quantity [0..1]
}

class "epo-cat:ItemModel" {
  epo:hasName : rdfs:Literal [1..1]
}

class "epo-cat:ItemRelation" {
  epo-cat:hasFactor : xsd:decimal [0..1]
  epo-cat:isRelatedToItem : epo-cat:Item [1]
}

class "epo-cat:ItemReplacement" {

}

class "epo-cat:ItemRequirement" {

}

class "epo-cat:Manufacturer" {
  epo-cat:hasContractor : epo:Contractor [0..*]
  epo:hasManufacturerID : epo:Identifier [0..1]
}

class "epo-cat:Price" {
  epo-cat:hasBaseQuantity : epo:Quantity [0..1]
  epo-cat:hasDeliveryLocation : dct:Location [0..1]
  epo-cat:hasExpectedDeliveryTime : epo:Duration [0..1]
  epo-cat:hasNetMonetaryValue : epo:MonetaryValue [1]
  epo-cat:hasOrderabableUnitFactorRate : epo:Quantity [0..1]
  epo-cat:hasPriceValidity : epo:Period [1]
  epo-cat:hasQuantityThreshold : epo:Quantity [0..1]
}

class "epo-cat:ProductSpecification" {

}

class "epo-cat:activity-code" {

}

class "epo-cat:orderable-unit" {

}

class "epo-cat:transaction-conditions" {

}

class "epo-cat:vat-category" {

}

@enduml
