
@startuml
class "epo-ord:Beneficiary" {

}

class "epo-ord:Consignee" {

}

class "epo-ord:ContractInformation" {
  epo-ord:concernsContract : epo:Contract [1]
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}

class "epo-ord:DeliveryInformation" {
  epo-ful:hasShippingMark : rdfs:Literal [0..*]
  epo-ord:concernsConsignee : epo-ord:Consignee [0..1]
  epo-ord:concernsPlaceOfDelivery : dct:Location [0..1]
  epo-ord:concernsPlaceOfStorage : dct:Location [0..1]
  epo-ord:hasDeliveryPeriod : epo:Period [0..1]
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
  epo:concernsBeneficiary : epo-ord:Beneficiary [0..1]
}

class "epo-ord:DiscountInformation" {
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}

class "epo-ord:Invoicee" {

}

class "epo-ord:Order" {
  epo-cat:specifiesChargeInformation : epo-cat:ChargeInformation [0..*]
  epo-ord:comprisesOrderLine : epo-ord:OrderLine [1..*]
  epo-ord:invoicedToInvoicee : epo-ord:Invoicee [0..1]
  epo-ord:isSubmittedByBuyer : epo:Buyer [1]
  epo-ord:isSubmittedToSeller : epo-ord:Seller [1]
  epo-ord:refersToCatalogue : epo-cat:Catalogue [0..*]
  epo-ord:specifiesContractInformation : epo-ord:ContractInformation [0..*]
  epo-ord:specifiesDeliveryInformation : epo-ord:DeliveryInformation [1..*]
  epo-ord:specifiesDiscountInformation : epo-ord:DiscountInformation [0..*]
  epo-ord:specifiesOriginatorInformation : epo-ord:OriginatorInformation [0..1]
  epo-ord:supersedesOrder : epo-ord:Order [0..1]
  epo:hasValidityPeriod : epo:Period [0..1]
}

class "epo-ord:OrderLine" {
  epo-cat:hasOrderQuantity : epo:Quantity [1]
  epo-cat:hasPrice : epo-cat:Price [0..1]
  epo-cat:specifiesItem : epo-cat:Item [1]
  epo-ord:refersToCatalogueLine : epo-cat:CatalogueLine [0..1]
}

class "epo-ord:Originator" {

}

class "epo-ord:OriginatorInformation" {
  epo-ord:concernsOriginator : epo-ord:Originator [1]
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}

class "epo-ord:PriceModifierInformation" {
  epo-cat:hasFixedAmount : epo:MonetaryValue [0..1]
  epo-cat:hasPricePercentage : xsd:decimal [0..1]
}

class "epo-ord:Seller" {

}

@enduml
