
@startuml
class "epo:AwardOutcome" {
  epo:hasAwardedValue epo:MonetaryValue
}

class "epo:MonetaryValue" {
  epo:hasAmountValue xsd:decimal
  epo:hasCurrency at-voc:currency
}

class "epo:Document" {
  dct:title rdf:PlainLiteral
  epo:hasPublicationDate xsd:date
}

class "epo:Notice" {
  epo:refersToLot epo:Lot
  epo:refersToProcedure epo:Procedure
}

class "epo:Lot" {
    epo:specifiesProcurementCriterion epo:ProcurementCriterion
  epo:isSubjectToLotSpecificTerm epo:LotSpecificTerm
}

class "epo:LotAwardOutcome" {
  epo:concernsLot epo:Lot
}

"epo:AwardOutcome" <|-- "epo:LotAwardOutcome"
"epo:Document" <|-- "epo:Notice"
"epo:Notice" --> "epo:Lot"
"epo:LotAwardOutcome" --> "epo:Lot"
"epo:AwardOutcome" --> "epo:MonetaryValue"
@enduml
