
@startuml
class "epo-not:CompetitionNotice" {
  epo-not:announcesLot : epo:Lot [1..*]
  epo-not:announcesLotGroup : epo:LotGroup [0..*]
  epo-not:announcesProcedure : epo:Procedure [1]
  epo-not:announcesRole : epo:AgentInRole [1..*]
}
class "epo-not:CompletionNotice" {

}
class "epo-not:ContractModificationNotice" {
  epo-not:refersToContractToBeModified : epo:Contract [1]
}
class "epo-not:DirectAwardPrenotificationNotice" {
  epo-not:announcesProcedure : epo:Procedure [1]
}
class "epo-not:PlanningNotice" {
  epo-not:announcesPlannedProcurementPart : epo:PlannedProcurementPart [0..*]
}
class "epo-not:ResultNotice" {
  epo-not:announcesContract : epo:Contract [0..1]
  epo-not:announcesLotAwardOutcome : epo:LotAwardOutcome [0..*]
  epo-not:announcesLotGroupAwardInformation : epo:LotGroupAwardInformation [0..*]
  epo-not:announcesNonPublishedElement : epo:PublicationProvision [0..*]
  epo-not:announcesNoticeAwardInformation : epo:NoticeAwardInformation [0..1]
  epo-not:announcesRole : epo:AgentInRole [0..*]
  epo-not:announcesTender : epo:Tender [0..*]
  epo-not:refersToLot : epo:Lot [1..*]
  epo-not:refersToLotGroup : epo:LotGroup [0..*]
  epo-not:refersToProcedureTerm : epo:ProcedureTerm [0..1]
  epo-not:refersToReviewTerm : epo:ReviewTerm [0..1]
  epo-not:refersToRole : epo:AgentInRole [1..*]
}
"epo:Notice" <|-- "epo-not:CompetitionNotice"
"epo:Notice" <|-- "epo-not:CompletionNotice"
"epo:Notice" <|-- "epo-not:ContractModificationNotice"
"epo:Notice" <|-- "epo-not:DirectAwardPrenotificationNotice"
"epo:Notice" <|-- "epo-not:PlanningNotice"
"epo:Notice" <|-- "epo-not:ResultNotice"
@enduml
