
@startuml
class "epo:TenderDocument" {
  epo:hasSubmissionTerm : epo:SubmissionTerm [1]
}
class "epo:RequestForClarification" {

}
class "epo:ExpressionOfInterest" {

}
class "epo:RequestForParticipation" {

}
class "epo:AccessTerm" {
  epo:AdditionalInformationDeadline : epo:DateTime [0..1]
  epo:hasRestrictedAccessAddress  : epo:Channel [0..*]
  epo:ProcurementDocumentLandingPage : epo:URI [0..1]
  epo:SomeProcurementDocumentRestricted : epo:Indicator [0..1]
  epo:SomeProcurementDocumentRestrictedJustification : epo:Text [0..*]
}
class "epo:Address" {
  epo:AdditionalStreetName : epo:Text [0..*]
  epo:BlockName : epo:Text [0..*]
  epo:BuildingName : epo:Text [0..*]
  epo:BuildingNumber : epo:Text [0..*]
  epo:CityName : epo:Text [0..*]
  epo:CitySubdivisionName : epo:Text [0..*]
  epo:CountryCode : epo:Code [0..1]
  epo:CountryCode : epo:Code [1..1]
  epo:CountrySubentity : epo:Text [0..*]
  epo:CountrySubentityCode : epo:Code [0..1]
  epo:Department : epo:Text [0..*]
  epo:District : epo:Text [0..*]
  epo:Floor : epo:Text [0..*]
  epo:has : epo:LocationCoordinate [0..1]
  epo:hasCountryCode : at-voc:country [1]
  epo:hasCountryCode : at-voc:country [0..1]
  epo:hasCountrySubentityCode : at-voc:nuts [0..1]
  epo:ID : epo:Identifier [0..1]
  epo:InhouseMail : epo:Text [0..*]
  epo:MarkAttention : epo:Text [0..*]
  epo:MarkCare : epo:Text [0..*]
  epo:PlotIdentification : epo:Text [0..*]
  epo:PostalZone : epo:Text [0..*]
  epo:Postbox : epo:Text [0..*]
  epo:Region : epo:Text [0..*]
  epo:Room : epo:Text [0..*]
  epo:StreetName : epo:Text [0..*]
  epo:TimezoneOffset : epo:Text [0..*]
}
class "epo:Agent" {
  epo:Alias : epo:Text [0..*]
  epo:delegatesAncillaryActivitiesOn : epo:Agent [0..*]
  epo:ID : epo:Identifier [0..*]
  epo:isCreatorOf : epo:Document [1..*]
  epo:playsRole : epo:Role [0..*]
  epo:provides : epo:RegulatoryFrameworkInformation [0..*]
}
class "epo:AwardCriterion" {
  epo:AwardCriterionType : epo:Code [0..1]
  epo:Description : epo:Text [0..*]
  epo:FixedValue : epo:Numeric [0..1]
  epo:FixedValueType : epo:Code [0..1]
  epo:Formula : epo:Text [0..*]
  epo:hasAwardCriterionType : at-voc:award-criterion-type [0..1]
  epo:hasFixedValueType : at-voc:number-fixed [0..1]
  epo:hasThresholdType : at-voc:number-threshold [0..*]
  epo:hasWeightValueType : at-voc:number-weight [0..1]
  epo:ID : epo:Identifier [1..1]
  epo:isUsedToAward : epo:LotGroup [0..*]
  epo:isUsedToAward : epo:Lot [0..*]
  epo:ThresholdType : epo:Code [0..*]
  epo:ThresholdValue : epo:Numeric [0..1]
  epo:WeightValue : epo:Numeric [0..1]
  epo:WeightValueType : epo:Code [0..1]
  epo:WeigthingJustification : epo:Text [0..*]
}
class "epo:AwardDecision" {
  epo:AwardDecisionDate : epo:Date [1..1]
  epo:AwardStatus : epo:Code [1..1]
  epo:has : epo:Winner [0..*]
  epo:hasAwardStatus : at-voc:winner-selection-status [1]
  epo:hasNonAwardJustification : at-voc:non-award-justification [1]
  epo:hasWinning : epo:TenderLot [0..*]
  epo:isReferredByA : epo:Contract [1]
  epo:Justification : epo:Text [0..*]
  epo:NonAwardJustification : epo:Code [1..1]
  epo:refersTo : epo:LotGroup [0..*]
  epo:refersTo : epo:Lot [0..*]
}
class "epo:Business" {
  epo:hasBeneficialOwner : epo:Person [0..*]
  epo:hasSize : at-voc:economic-operator-size [0..1]
  epo:ListedCompany : epo:Indicator [0..1]
  epo:Size : epo:Code [0..1]
}
class "epo:Buyer" {
  epo:ActivityDescription : epo:Text [0..*]
  epo:appoints : epo:EvaluationBoard [0..1]
  epo:BuyerLegalType : epo:Code [0..1]
  epo:BuyerLegalTypeDescription : epo:Text [0..*]
  epo:ContractingEntity : epo:Indicator [0..1]
  epo:executesPayment : epo:Lot [0..*]
  epo:has : epo:BuyerProfile [0..1]
  epo:hasBuyerLegalType : at-voc:buyer-legal-type [1]
  epo:hasMainActivityType : at-voc:main-activity [0..1]
  epo:isGroupLeader : epo:Lot [0..*]
  epo:MainActivityType : epo:Code [0..1]
  epo:makesDecsion : epo:AwardDecision [0..*]
  epo:plans : epo:PlannedProcurementPart [0..*]
  epo:processesRequestsToParticipate : epo:Lot [0..*]
  epo:processesTenders : epo:Lot [0..*]
  epo:providesAdditionalInformationAboutProcurementProcedure : epo:Lot [0..*]
  epo:providesOfflineAccessToProcurementDocuments : epo:Lot [0..*]
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  epo:receivesRequestsToParticipate : epo:Lot [0..*]
  epo:receivesTenders : epo:Lot [0..*]
  epo:signsContract : epo:Lot [0..*]
  epo:usesBudgetToPayContract : epo:Lot [0..*]
  reg2015:executesPayment : epo:Procedure [0..*]
  reg2015:isGroupLeader : epo:Procedure [0..*]
  reg2015:processesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:processesTenders : epo:Procedure [0..*]
  reg2015:providesAdditionalInformationAboutProcurementProcedure : epo:Procedure [0..*]
  reg2015:providesMoreInformationOnTimeLimitsForReviewProcedures : epo:Procedure [0..*]
  reg2015:providesOfflineAccessToProcurementDocuments : epo:Procedure [0..*]
  reg2015:receivesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:receivesTenders : epo:Procedure [0..*]
  reg2015:signsContract : epo:Procedure [0..*]
  reg2015:usesBudgetToPayContract : epo:Procedure [0..*]
}
class "epo:BuyerProfile" {
  epo:URL : epo:URI [1..1]
}
class "epo:BuyerProfileNotice" {

}
class "epo:CallForCompetition" {
  epo:isNotifiedThrough : epo:Notice [0..*]
}
class "epo:CallForExpressionOfInterest" {

}
class "epo:CentralPurchasingBody" {
  epo:CPBType : epo:Code [0..1]
  epo:hasCentralPurchasingBodyType : epo:cpb-type [0..1]
}
class "epo:Change" {
  epo:ChangeReason : epo:Code [1..1]
  epo:DateTime : epo:DateTime [1..1]
  epo:Description : epo:Text [0..*]
  epo:hasChangeElement : epo:ResourceElement [0..*]
  epo:hasChangeReason : at-voc:change-corrig-justification [1]
  epo:ProcurementDocumentChanged : epo:Indicator [0..1]
  epo:Reason : epo:Text [0..*]
  epo:refersToADifferent : epo:Document [0..*]
}
class "epo:Channel" {
  epo:AdditionalInformation : epo:Text [0..*]
  epo:Description : epo:Text [0..*]
  epo:Endpoint : epo:URI [0..1]
  epo:Name : epo:Text [0..*]
  epo:URL : epo:URI [1..1]
}
class "epo:ContactPoint" {
  epo:Description : epo:Text [0..*]
  epo:Email : epo:URI [0..1]
  epo:Fax : epo:Text [0..*]
  epo:has : epo:Channel [0..*]
  epo:hasContactPersonRole : epo:Role [0..*]
  epo:hasLocation : epo:Location [0..1]
  epo:InternetAddress : epo:URI [0..1]
  epo:Telephone : epo:Text [0..*]
}
class "epo:Contract" {
  epo:attaches : epo:Document [0..*]
  epo:ContractConclusionDate : epo:Date [0..1]
  epo:EntryintoForceDate : epo:Date [0..1]
  epo:hasContractPurpose : epo:Purpose [1]
  epo:hasDuration : epo:Period [1]
  epo:hasDurationEvaluationPeriod : epo:Period [1]
  epo:hasEstimatedDuration : epo:Period [1]
  epo:hasProcurementValue : epo:Value [1]
  epo:ID : epo:Identifier [1..1]
  epo:isFundedBy : epo:Fund [0..*]
  epo:isSignedBy : epo:Agent [0..*]
  epo:mentions : epo:LotGroup [0..*]
  epo:refersTo : epo:Tender [1..*]
  epo:refersTo : epo:Lot [1..*]
  epo:refersToSignatory : epo:Winner [1..*]
  epo:Title : epo:Text [0..*]
}
class "epo:ContractAwardNotice" {
  epo:hasTotalFrameworkValue : epo:Value [0..1]
  epo:hasTotalValue : epo:Value [0..1]
  epo:notifiesAwardResult : epo:AwardDecision [1]
  epo:summarisesProcedure : epo:Procedure [0..*]
}
class "epo:ContractModificationNotice" {
  epo:Description : epo:Text [0..*]
  epo:hasContractModficationJustification : at-voc:modification-justification [1]
  epo:Justification : epo:Text [0..*]
  epo:ModificationReason : epo:Code [1..1]
  epo:modifies : epo:Contract [1]
  epo:refersTo : epo:ContractAwardNotice [1]
}
class "epo:ContractNotice" {
  epo:Recurrence : epo:Indicator [0..1]
  epo:RecurrenceDescription : epo:Text [0..*]
  epo:RecurrenceDescription : epo:Text [0..1]
}
class "epo:Contractor" {

}
class "epo:ContractTerm" {
  epo:BroadPlaceOfPerformance : epo:Code [0..1]
  epo:ContractorLegalFormRequirement : epo:Indicator [0..1]
  epo:ContractorLegalFormRequirementDescription : epo:Text [0..*]
  epo:EInvoicing : epo:Indicator [0..1]
  epo:EOrdering : epo:Indicator [0..1]
  epo:EPayment : epo:Indicator [0..1]
  epo:hasBroadPlaceOfPerformance : at-voc:other-place-service [0..1]
  epo:hasReservedExecution : at-voc:applicability [1]
  epo:hasSpecificPlaceOfPerformance : epo:Address [0..*]
  epo:includes : epo:SubcontractTerm [0..1]
  epo:MaximumNumberOfRenewals : epo:Numeric [0..1]
  epo:PaymentArrangement : epo:Text [0..*]
  epo:PerformanceConditions : epo:Text [0..*]
  epo:PlaceOfPerformanceAdditionalInformation : epo:Text [0..*]
  epo:RenewalDescription : epo:Text [0..*]
  epo:RenewalIndicator : epo:Indicator [0..1]
  epo:ReservedExecution : epo:Code [0..1]
}
class "epo:DesignContestRegimeTerm" {
  epo:appliesTo : epo:Lot [0..*]
  epo:definesPrize : epo:Prize [0..*]
  epo:FollowupContract : epo:Indicator [0..1]
  epo:FollowupContractInformation : epo:Text [0..*]
  epo:JuryDecisionBinding : epo:Indicator [0..1]
  epo:ParticipationPayment : epo:Numeric [0..1]
}
class "epo:DirectAwardTerm" {
  epo:hasJustificationType : at-voc:direct-award-justification [0..1]
  epo:Justification : epo:Text [0..*]
  epo:JustificationType : epo:Code [0..1]
  epo:refersToPreviousProcedureLots : epo:Lot [0..*]
}
class "epo:Document" {
  epo:changeRefersToInstance : epo:Document [0..*]
  epo:DispatchDate : epo:Date [0..1]
  epo:hasChange : epo:Change [0..*]
  epo:hasNonPublishedElement : epo:PublicationProvision [0..*]
  epo:hasOfficialLanguage : at-voc:language [1..*]
  epo:hasRestrictedCommunicationJustification : at-voc:communication-justification [1]
  epo:hasUnofficialLanguage : at-voc:language [0..*]
  epo:ID : epo:Identifier [0..*]
  epo:includes : epo:RegulatoryFrameworkInformation [0..*]
  epo:IsMadeAvailableVia : epo:Channel [0..*]
  epo:isSubmittedBy : epo:Agent [0..1]
  epo:OfficialLanguage : epo:Code [0..*]
  epo:ReceptionDate : epo:Date [0..1]
  epo:refersToPrevious : epo:Document [0..*]
  epo:relatesTo : epo:Procedure [0..*]
  epo:RestrictedCommunicationsJustification : epo:Code [0..1]
  epo:UnofficialLanguage : epo:Code [0..*]
  epo:UUID : epo:Identifier [1..1]
}
class "epo:DynamicPurchaseSystemTechnique" {
  epo:DPSTermination : epo:Indicator [0..1]
}
class "epo:EAuctionTechnique" {
  epo:EAuctionUsage : epo:Code [0..1]
  epo:hasEAuctionUsage : at-voc:usage [0..1]
}
class "epo:EconomicOperator" {
  epo:EORoleType : epo:Code [1..*]
  epo:hasEORoleType : espd:eo-role-type [1..*]
}
class "epo:EvaluationBoard" {
  epo:EvaluationGroupType : epo:Code [0..1]
  epo:has : epo:ExclusionGround [0..*]
  epo:hasEvaluationGroupType : epo:evaluation-group-type [0..1]
  epo:hasEvaluationMember : epo:Agent [1..*]
  epo:isAssignedForEvaluationOf : epo:Lot [0..*]
}
class "epo:EvaluationTerm" {
  epo:AwardCriteriaEvaluationFormula : epo:Text [0..*]
  epo:OverallCostAwardCriteriaPonderation : epo:Numeric [0..1]
  epo:OverallPriceAwardCriteriaPonderation : epo:Numeric [0..1]
  epo:OverallQualityAwardCriteriaPonderation : epo:Numeric [0..1]
}
class "epo:ExclusionGround" {
  epo:PersonalSituationCondition : epo:Text [0..*]
}
class "epo:FrameworkAgreement" {

}
class "epo:FrameworkAgreementTechnique" {
  epo:isConcludedBy : epo:FrameworkAgreement [0..*]
  epo:isOrganisedIn : epo:LotGroup [0..*]
  epo:uses : epo:EAuctionTechnique [0..*]
}
class "epo:FrameworkAgreementTerm" {
  epo:appliesTo : epo:Lot [1..*]
  epo:BuyerCoverage : epo:Text [0..*]
  epo:DurationExtensionJustification : epo:Text [0..*]
  epo:FrameworkAgreementType : epo:Code [1..1]
  epo:hasFrameworkAgreementType : at-voc:framework-agreement [1]
  epo:hasOverallMaximumValue : epo:Value [0..1]
  epo:isUsedBy : epo:LotGroup [0..*]
  epo:MaximumNumberOfAwardedTenderers : epo:Quantity [0..1]
}
class "epo:Fund" {
  epo:ID : epo:Identifier [1..1]
  epo:Name : epo:Text [0..*]
  epo:URL : epo:URI [0..1]
}
class "epo:GreenProcurement" {
  epo:fulfillsRequirement : at-voc:environmental-impact [1..*]
  epo:FulfillsRequirement : epo:Code [1..*]
}
class "epo:InnovativeProcurement" {
  epo:fulfillsRequirement : at-voc:innovative-acquisition [1..*]
  epo:FulfillsRequirement : epo:Code [1..*]
}
class "epo:Item" {
  epo:CountryOfOrigin : epo:Code [0..1]
  epo:Description : epo:Text [0..*]
  epo:hasCountryOfOrigin : at-voc:country [1..*]
  epo:ID : epo:Identifier [1..1]
  epo:Name : epo:Text [0..*]
}
class "epo:Location" {
  epo:hasPostalAddress : epo:Address [0..1]
}
class "epo:LocationCoordinate" {
  epo:Altitude : epo:Text [0..*]
  epo:Latitude : epo:Text [0..*]
  epo:Longitude : epo:Text [0..*]
}
class "epo:Lot" {
  epo:AdditionalInformation : epo:Text [0..*]
  epo:applies : epo:MultipleStageProcedureTerm [0..1]
  epo:applies : epo:ContractTerm [0..1]
  epo:AwardDateScheduled : epo:Date [0..1]
  epo:contributesToImplement : epo:ProjectProcurement [1]
  epo:Description : epo:Text [0..*]
  epo:EstimatedTenderInvitationDate : epo:Date [0..1]
  epo:GPAUsage : epo:Indicator [0..1]
  epo:has : epo:Purpose [1]
  epo:has : epo:OpeningTerm [1]
  epo:hasAwardedEstimatedValue : epo:Value [0..1]
  epo:hasAwardedValue : epo:Value [0..1]
  epo:hasContractDuration : epo:Period [0..1]
  epo:hasEstimatedBuyerConcessionRevenue : epo:Value [0..1]
  epo:hasEstimatedUserConcessionRevenue : epo:Value [0..1]
  epo:hasEstimatedValue : epo:Value [0..1]
  epo:hasReservedProcurement : at-voc:reserved-procurement [0..*]
  epo:hasTenderEvaluationTerm : epo:EvaluationTerm [0..1]
  epo:hasVariantPermission : at-voc:permission [0..1]
  epo:ID : epo:Identifier [0..1]
  epo:involvesOverallStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:isAwardedTo : epo:TenderLot [0..*]
  epo:isFundedBy : epo:Fund [0..*]
  epo:isGroupedIn : epo:LotGroup [0..*]
  epo:isProvidedWithin : at-voc:requirement-stage [0..*]
  epo:isReferredToIn : epo:ProcurementDocument [1..*]
  epo:PerformingStafQualificationInformation : epo:Code [0..*]
  epo:providesAdditionalInformation : epo:StatisticalInformation [0..1]
  epo:refersTo : epo:PlannedProcurementPart [0..*]
  epo:refersTo : epo:Item [0..*]
  epo:requires : epo:SecurityClearanceTerm [0..*]
  epo:ReservedProcurement : epo:Code [0..*]
  epo:SMESuitable : epo:Indicator [0..1]
  epo:Title : epo:Text [0..*]
  epo:usesAdhoc : epo:Channel [0..*]
  epo:VariantsPermission : epo:Code [0..1]
}
class "epo:LotGroup" {
  epo:Description : epo:Text [0..*]
  epo:hasAwardedValue : epo:Value [0..1]
  epo:hasEstimatedValue : epo:Value [0..1]
  epo:ID : epo:Identifier [1..1]
  epo:isAwardedTo : epo:Tender [0..*]
  epo:Title : epo:Text [0..*]
}
class "epo:Mediator" {

}
class "epo:MultipleStageProcedureTerm" {
  epo:EstimatedInvitationToExpressInterestDate : epo:Date [0..1]
  epo:EstimatedInvitationToTenderDate : epo:Date [0..1]
  epo:MaximumCandidates : epo:Indicator [0..1]
  epo:MaximumNumberOfCandidates : epo:Numeric [0..1]
  epo:MinimumNumberOfCandidates : epo:Numeric [0..1]
  epo:NoNegotiationNecessary : epo:Indicator [0..1]
  epo:SuccessiveReduction : epo:Indicator [0..1]
}
class "epo:Notice" {
  epo:DPSScope : epo:Code [0..1]
  epo:FormType : epo:Code [1..1]
  epo:hasDPSScope : at-voc:dps-usage [0..1]
  epo:hasFormType : at-voc:form-type [1]
  epo:hasNotificationPhasesType : epo:notification-phases-content-types [0..1]
  epo:NotificationContentType : epo:Code [0..1]
  epo:notifies : epo:Procedure [0..*]
  epo:PreferredPublicationDate : epo:Date [0..1]
  epo:PublicationDate : epo:Date [1..1]
  epo:relatesToNotice : epo:Notice [0..*]
}
class "epo:OpeningTerm" {
  epo:hasOpeningPlace : epo:Address [0..1]
  epo:hasVirtualTenderOpeningAddress : epo:Channel [0..1]
  epo:OpeningDateTime : epo:DateTime [1..1]
  epo:OpeningDescription : epo:Text [0..*]
  epo:OpeningURL : epo:URI [0..1]
}
class "epo:Organisation" {
  epo:hasDefaultContactPoint : epo:ContactPoint [1..*]
  epo:hasLocation : epo:Location [0..*]
  epo:isMemberOf : epo:OrganisationGroup [0..*]
  epo:leadOf : epo:OrganisationGroup [0..*]
  epo:LegalFormType : epo:Code [0..1]
  epo:Name : epo:Text [0..*]
}
class "epo:OrganisationGroup" {
  epo:GroupType : epo:Text [0..*]
}
class "epo:Reviewer" {
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  reg2015:providesMoreInformationOnTimeLimitsForReviewProcedures : epo:Procedure [0..*]
}
class "epo:Period" {
  epo:Description : epo:Text [0..*]
  epo:DurationMeasure : epo:Measure [0..1]
  epo:EndDate : epo:Date [0..1]
  epo:EndTime : epo:Time [0..1]
  epo:hasTimePeriods : at-voc:timeperiod [1..*]
  epo:StartDate : epo:Date [0..1]
  epo:StartTime : epo:Time [0..1]
}
class "epo:Technique" {
  epo:Description : epo:Text [0..*]
  epo:hasValidityPeriod : epo:Period [0..1]
  epo:ID : epo:Identifier [0..1]
  epo:isAvailableVia : epo:Channel [0..*]
  epo:isUsedBy : epo:Lot [1..*]
}
class "epo:SubmissionTerm" {
  epo:AdvancedElectronicSignatureRequired : epo:Indicator [0..1]
  epo:ECataloguePermission : epo:Code [0..1]
  epo:ESubmissionPermission : epo:Code [0..1]
  epo:GuaranteeDescription : epo:Text [0..*]
  epo:GuaranteeRequired : epo:Indicator [0..1]
  epo:hasECataloguePermission : at-voc:permission [0..1]
  epo:hasESubmissionPermission : at-voc:permission [0..1]
  epo:hasLanguage : at-voc:language [0..*]
  epo:hasLateSubmissionPermission : at-voc:missing-info-submission [0..1]
  epo:hasNonElectronicSubmissionJustification : at-voc:communication-justification [0..*]
  epo:hasSubmissionCommunicationMeans : epo:Channel [0..*]
  epo:hasTenderSubcontractingInformation : at-voc:subcontracting-indication [0..*]
  epo:hasValidityPeriod : epo:Period [0..1]
  epo:isAppliedBy : epo:Lot [1..*]
  epo:Language : epo:Code [0..*]
  epo:LateSubmissionInformationDescription : epo:Text [0..*]
  epo:LateSubmissionPermission : epo:Code [0..1]
  epo:MultipleTenderSubmissionAllowed : epo:Indicator [0..1]
  epo:NonElectronicSubmissionDescription : epo:Text [0..*]
  epo:NonElectronicSubmissionJustification : epo:Code [0..*]
  epo:ReceiptDeadline : epo:DateTime [1..1]
  epo:TenderSubcontractingInformation : epo:Code [0..*]
}
class "epo:Period" {
  epo:Description : epo:Text [0..*]
  epo:DurationMeasure : epo:Measure [0..1]
  epo:EndDate : epo:Date [0..1]
  epo:EndTime : epo:Time [0..1]
  epo:hasTimePeriods : at-voc:timeperiod [1..*]
  epo:StartDate : epo:Date [0..1]
  epo:StartTime : epo:Time [0..1]
}
class "epo:Person" {
  epo:AlternativeName : epo:Text [0..*]
  epo:BirthFamilyName : epo:Text [0..*]
  epo:DateOfBirth : epo:Date [0..1]
  epo:DateOfDeath : epo:Date [0..1]
  epo:FamilyName : epo:Text [0..*]
  epo:FullName : epo:Text [0..*]
  epo:GivenName : epo:Text [0..*]
  epo:hasCountryOfBirth : epo:Location [1]
  epo:hasLegalLocation : epo:Location [0..1]
  epo:hasNationality : at-voc:country [0..*]
  epo:ID : epo:Identifier [0..1]
  epo:Nationality : epo:Code [0..*]
  epo:PatronimicName : epo:Text [0..*]
}
class "epo:PlannedProcurementPart" {
  epo:AdditionalInformation : epo:Text [0..*]
  epo:Description : epo:Text [0..*]
  epo:has : epo:ContractTerm [0..1]
  epo:has : epo:AccessTerm [0..1]
  epo:hasLegalBasisID : at-voc:legal-basis [0..*]
  epo:hasPlannedPeriod : epo:Period [0..1]
  epo:hasPurpose : epo:Purpose [1]
  epo:ID : epo:Identifier [1..1]
  epo:involvesOverallStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:isFundedWith : epo:Fund [0..*]
  epo:LegalBasis : epo:Code [0..*]
  epo:LegalBasisID : epo:URI [0..*]
  epo:refersTo : epo:Document [0..*]
  epo:SMESuitable : epo:Indicator [0..1]
  epo:Title : epo:Text [0..*]
  epo:uses : epo:Channel [0..*]
}
class "epo:MultipleStageProcedureTerm" {
  epo:EstimatedInvitationToExpressInterestDate : epo:Date [0..1]
  epo:EstimatedInvitationToTenderDate : epo:Date [0..1]
  epo:MaximumCandidates : epo:Indicator [0..1]
  epo:MaximumNumberOfCandidates : epo:Numeric [0..1]
  epo:MinimumNumberOfCandidates : epo:Numeric [0..1]
  epo:NoNegotiationNecessary : epo:Indicator [0..1]
  epo:SuccessiveReduction : epo:Indicator [0..1]
}
class "epo:ContractTerm" {
  epo:BroadPlaceOfPerformance : epo:Code [0..1]
  epo:ContractorLegalFormRequirement : epo:Indicator [0..1]
  epo:ContractorLegalFormRequirementDescription : epo:Text [0..*]
  epo:EInvoicing : epo:Indicator [0..1]
  epo:EOrdering : epo:Indicator [0..1]
  epo:EPayment : epo:Indicator [0..1]
  epo:hasBroadPlaceOfPerformance : at-voc:other-place-service [0..1]
  epo:hasReservedExecution : at-voc:applicability [1]
  epo:hasSpecificPlaceOfPerformance : epo:Address [0..*]
  epo:includes : epo:SubcontractTerm [0..1]
  epo:MaximumNumberOfRenewals : epo:Numeric [0..1]
  epo:PaymentArrangement : epo:Text [0..*]
  epo:PerformanceConditions : epo:Text [0..*]
  epo:PlaceOfPerformanceAdditionalInformation : epo:Text [0..*]
  epo:RenewalDescription : epo:Text [0..*]
  epo:RenewalIndicator : epo:Indicator [0..1]
  epo:ReservedExecution : epo:Code [0..1]
}
class "epo:Fund" {
  epo:ID : epo:Identifier [1..1]
  epo:Name : epo:Text [0..*]
  epo:URL : epo:URI [0..1]
}
class "epo:ProcurementServiceProvider" {
  epo:executesPayment : epo:Lot [0..*]
  epo:isGroupLeader : epo:Lot [0..*]
  epo:manages : epo:BuyerProfile [0..1]
  epo:processesRequestsToParticipate : epo:Lot [0..*]
  epo:processesTenders : epo:Lot [0..*]
  epo:providesAdditionalInformationAboutProcurementProcedure : epo:Lot [0..*]
  epo:providesOfflineAccessToProcurementDocuments : epo:Lot [0..*]
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  epo:receivesRequestsToParticipate : epo:Lot [0..*]
  epo:receivesTenders : epo:Lot [0..*]
  epo:signsContract : epo:Lot [0..*]
  epo:usesBudgetToPayContract : epo:Lot [0..*]
  reg2015:executesPayment : epo:Procedure [0..*]
  reg2015:isGroupLeader : epo:Procedure [0..*]
  reg2015:processesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:processesTenders : epo:Procedure [0..*]
  reg2015:providesAdditionalInformationAboutProcurementProcedure : epo:Procedure [0..*]
  reg2015:providesOfflineAccessToProcurementDocuments : epo:Procedure [0..*]
  reg2015:receivesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:receivesTenders : epo:Procedure [0..*]
  reg2015:signsContract : epo:Procedure [0..*]
  reg2015:usesBudgetToPayContract : epo:Procedure [0..*]
}
class "epo:Role" {
  epo:Description : epo:Text [0..*]
  epo:has : epo:ContactPoint [0..*]
  epo:Title : epo:Text [0..*]
  reg2015:isInvolvedIn : epo:Procedure [0..*]
}
class "epo:Channel" {
  epo:AdditionalInformation : epo:Text [0..*]
  epo:Description : epo:Text [0..*]
  epo:Endpoint : epo:URI [0..1]
  epo:Name : epo:Text [0..*]
  epo:URL : epo:URI [1..1]
}
class "epo:PriorInformationNotice" {
  epo:EstimatedContractNoticePublicationDate : epo:Date [1..1]
  epo:EstimatedContractNoticePublicationDate : epo:Date [0..1]
  epo:notifies : epo:PlannedProcurementPart [0..*]
}
class "epo:Prize" {
  epo:PrizeRank : epo:Numeric [0..1]
  epo:PrizeValue : epo:Amount [0..1]
}
class "epo:Procedure" {
  epo:Accelerated : epo:Indicator [0..1]
  epo:AcceleratedProcedureJustification : epo:Text [0..*]
  epo:ChoiceJustification : epo:Text [0..*]
  epo:CompetitionTermination : epo:Indicator [0..1]
  epo:Description : epo:Text [0..*]
  epo:DesignContest : epo:Indicator [0..1]
  epo:has : epo:ProcedureTerm [0..1]
  epo:has : epo:DirectAwardTerm [0..1]
  epo:hasEstimatedValue : epo:Value [1]
  epo:hasLegalBasis : at-voc:legal-basis [0..*]
  epo:hasLegalRegime : epo:legal-regime [0..*]
  epo:hasOverallPurpose : epo:Purpose [0..1]
  epo:hasProcedureType : at-voc:procurement-procedure-type [1]
  epo:hasTotalValue : epo:Value [1]
  epo:ID : epo:Identifier [1..1]
  epo:involvesOverallStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:isConcludedBy : epo:Contract [0..*]
  epo:isResponsiblityOf : epo:Buyer [1..*]
  epo:leadsTo : epo:Contract [1..*]
  epo:LegalBasis : epo:Code [0..1]
  epo:LegalBasis : epo:Code [0..*]
  epo:LegalBasisID : epo:URI [0..*]
  epo:LegalRegime : epo:Code [0..*]
  epo:LotMinimumSubmission : epo:Numeric [0..1]
  epo:LotSubmissionLimit : epo:Numeric [0..1]
  epo:MainFeature : epo:Text [0..*]
  epo:MaximumNumberOfLotsToBeAwarded : epo:Numeric [0..1]
  epo:ProcedureType : epo:Code [1..1]
  epo:specifies : epo:Lot [1..*]
  epo:Title : epo:Text [0..*]
  epo:uses : epo:ExclusionGround [0..*]
  epo:uses : epo:AccessTerm [0..*]
  reg2015:AdditionalInformation : epo:Text [0..*]
  reg2015:AwardedByCPB : epo:Code [0..1]
  reg2015:BuyerLegalType : epo:Code [0..1]
  reg2015:BuyerLegalTypeDescription : epo:Text [0..*]
  reg2015:BuyerMainActivity : epo:Code [0..1]
  reg2015:BuyerMainActivityDescription : epo:Text [0..*]
  reg2015:DeadlineTendersAndRequest : epo:DateTime [1..1]
  reg2015:EstimatedTenderAndRequestInvitationDate : epo:Date [0..1]
  reg2015:GPAUsage : epo:Indicator [0..1]
  reg2015:JointProcurement : epo:Indicator [0..1]
  reg2015:LanguagesTendersAndRequest : epo:Code [1..*]
  reg2015:LegalBasisDescription : epo:Text [0..*]
  reg2015:PerformingStaffQualificationInformation : epo:Indicator [0..1]
  reg2015:PublicationOfCallForCompetition : epo:Indicator [0..1]
  reg2015:VariantPermission : epo:Code [0..1]
  null : epo :Procurement Term 
  null : epo :Procedure 
  reg2015:applies : epo:FrameworkAgreementTerm [0..*]
  reg2015:applies : epo:ReviewTerm [0..*]
  reg2015:applies : epo:SelectionCriterion [0..*]
  reg2015:applies : epo:OpeningTerm [0..*]
  reg2015:applies : epo:ContractTerm [0..*]
  reg2015:applies : epo:SubmissionTerm [0..*]
  reg2015:has : epo:MultipleStageProcedureTerm [0..1]
  reg2015:hasBuyerLegalType : at-voc:buyer-legal-type [0..1]
  reg2015:hasCriteriaInProcurementDocument : epo:ProcurementCriterion [1..*]
  reg2015:hasFrameworkAgreementDuration : epo:Period [0..1]
  reg2015:hasReservedProcurement : at-voc:reserved-procurement [1..*]
  reg2015:isFundedBy : epo:Fund [0..*]
  reg2015:requires : epo:SecurityClearanceTerm [1..*]
  reg2015:uses : epo:Technique [0..*]
  reg2015:usesAdhoc : epo:Channel [0..*]
  reg2015:usesToAward : epo:AwardCriterion [0..*]
}
class "epo:OpeningTerm" {
  epo:hasOpeningPlace : epo:Address [0..1]
  epo:hasVirtualTenderOpeningAddress : epo:Channel [0..1]
  epo:OpeningDateTime : epo:DateTime [1..1]
  epo:OpeningDescription : epo:Text [0..*]
  epo:OpeningURL : epo:URI [0..1]
}
class "epo:SelectionCriterion" {
  epo:appliesTo : epo:LotGroup [0..*]
  epo:Formula : epo:Text [0..*]
  epo:hasSelectionCriterionType : at-voc:selection-criterion [0..1]
  epo:hasThresholdType : at-voc:number-threshold [0..*]
  epo:hasWeightValueType : at-voc:number-weight [0..*]
  epo:isAppliedBy : epo:Lot [0..*]
  epo:SelectionCriterionType : epo:Code [0..1]
  epo:ThresholdType : epo:Code [0..*]
  epo:ThresholdValue : epo:Numeric [1..1]
  epo:UsedForCandidateRestriction : epo:Indicator [0..1]
  epo:usedForReductionOfCandidates : epo:Lot [0..*]
  epo:WeightingJustification : epo:Text [0..*]
  epo:WeightValue : epo:Numeric [1..1]
  epo:WeightValueType : epo:Code [0..*]
}
class "epo:Procedure" {
  epo:Accelerated : epo:Indicator [0..1]
  epo:AcceleratedProcedureJustification : epo:Text [0..*]
  epo:ChoiceJustification : epo:Text [0..*]
  epo:CompetitionTermination : epo:Indicator [0..1]
  epo:Description : epo:Text [0..*]
  epo:DesignContest : epo:Indicator [0..1]
  epo:has : epo:ProcedureTerm [0..1]
  epo:has : epo:DirectAwardTerm [0..1]
  epo:hasEstimatedValue : epo:Value [1]
  epo:hasLegalBasis : at-voc:legal-basis [0..*]
  epo:hasLegalRegime : epo:legal-regime [0..*]
  epo:hasOverallPurpose : epo:Purpose [0..1]
  epo:hasProcedureType : at-voc:procurement-procedure-type [1]
  epo:hasTotalValue : epo:Value [1]
  epo:ID : epo:Identifier [1..1]
  epo:involvesOverallStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:isConcludedBy : epo:Contract [0..*]
  epo:isResponsiblityOf : epo:Buyer [1..*]
  epo:leadsTo : epo:Contract [1..*]
  epo:LegalBasis : epo:Code [0..1]
  epo:LegalBasis : epo:Code [0..*]
  epo:LegalBasisID : epo:URI [0..*]
  epo:LegalRegime : epo:Code [0..*]
  epo:LotMinimumSubmission : epo:Numeric [0..1]
  epo:LotSubmissionLimit : epo:Numeric [0..1]
  epo:MainFeature : epo:Text [0..*]
  epo:MaximumNumberOfLotsToBeAwarded : epo:Numeric [0..1]
  epo:ProcedureType : epo:Code [1..1]
  epo:specifies : epo:Lot [1..*]
  epo:Title : epo:Text [0..*]
  epo:uses : epo:ExclusionGround [0..*]
  epo:uses : epo:AccessTerm [0..*]
  reg2015:AdditionalInformation : epo:Text [0..*]
  reg2015:AwardedByCPB : epo:Code [0..1]
  reg2015:BuyerLegalType : epo:Code [0..1]
  reg2015:BuyerLegalTypeDescription : epo:Text [0..*]
  reg2015:BuyerMainActivity : epo:Code [0..1]
  reg2015:BuyerMainActivityDescription : epo:Text [0..*]
  reg2015:DeadlineTendersAndRequest : epo:DateTime [1..1]
  reg2015:EstimatedTenderAndRequestInvitationDate : epo:Date [0..1]
  reg2015:GPAUsage : epo:Indicator [0..1]
  reg2015:JointProcurement : epo:Indicator [0..1]
  reg2015:LanguagesTendersAndRequest : epo:Code [1..*]
  reg2015:LegalBasisDescription : epo:Text [0..*]
  reg2015:PerformingStaffQualificationInformation : epo:Indicator [0..1]
  reg2015:PublicationOfCallForCompetition : epo:Indicator [0..1]
  reg2015:VariantPermission : epo:Code [0..1]
  null : epo :Procurement Term 
  null : epo :Procedure 
  reg2015:applies : epo:FrameworkAgreementTerm [0..*]
  reg2015:applies : epo:ReviewTerm [0..*]
  reg2015:applies : epo:SelectionCriterion [0..*]
  reg2015:applies : epo:OpeningTerm [0..*]
  reg2015:applies : epo:ContractTerm [0..*]
  reg2015:applies : epo:SubmissionTerm [0..*]
  reg2015:has : epo:MultipleStageProcedureTerm [0..1]
  reg2015:hasBuyerLegalType : at-voc:buyer-legal-type [0..1]
  reg2015:hasCriteriaInProcurementDocument : epo:ProcurementCriterion [1..*]
  reg2015:hasFrameworkAgreementDuration : epo:Period [0..1]
  reg2015:hasReservedProcurement : at-voc:reserved-procurement [1..*]
  reg2015:isFundedBy : epo:Fund [0..*]
  reg2015:requires : epo:SecurityClearanceTerm [1..*]
  reg2015:uses : epo:Technique [0..*]
  reg2015:usesAdhoc : epo:Channel [0..*]
  reg2015:usesToAward : epo:AwardCriterion [0..*]
}
class "epo:Buyer" {
  epo:ActivityDescription : epo:Text [0..*]
  epo:appoints : epo:EvaluationBoard [0..1]
  epo:BuyerLegalType : epo:Code [0..1]
  epo:BuyerLegalTypeDescription : epo:Text [0..*]
  epo:ContractingEntity : epo:Indicator [0..1]
  epo:executesPayment : epo:Lot [0..*]
  epo:has : epo:BuyerProfile [0..1]
  epo:hasBuyerLegalType : at-voc:buyer-legal-type [1]
  epo:hasMainActivityType : at-voc:main-activity [0..1]
  epo:isGroupLeader : epo:Lot [0..*]
  epo:MainActivityType : epo:Code [0..1]
  epo:makesDecsion : epo:AwardDecision [0..*]
  epo:plans : epo:PlannedProcurementPart [0..*]
  epo:processesRequestsToParticipate : epo:Lot [0..*]
  epo:processesTenders : epo:Lot [0..*]
  epo:providesAdditionalInformationAboutProcurementProcedure : epo:Lot [0..*]
  epo:providesOfflineAccessToProcurementDocuments : epo:Lot [0..*]
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  epo:receivesRequestsToParticipate : epo:Lot [0..*]
  epo:receivesTenders : epo:Lot [0..*]
  epo:signsContract : epo:Lot [0..*]
  epo:usesBudgetToPayContract : epo:Lot [0..*]
  reg2015:executesPayment : epo:Procedure [0..*]
  reg2015:isGroupLeader : epo:Procedure [0..*]
  reg2015:processesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:processesTenders : epo:Procedure [0..*]
  reg2015:providesAdditionalInformationAboutProcurementProcedure : epo:Procedure [0..*]
  reg2015:providesMoreInformationOnTimeLimitsForReviewProcedures : epo:Procedure [0..*]
  reg2015:providesOfflineAccessToProcurementDocuments : epo:Procedure [0..*]
  reg2015:receivesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:receivesTenders : epo:Procedure [0..*]
  reg2015:signsContract : epo:Procedure [0..*]
  reg2015:usesBudgetToPayContract : epo:Procedure [0..*]
}
class "epo:AwardCriterion" {
  epo:AwardCriterionType : epo:Code [0..1]
  epo:Description : epo:Text [0..*]
  epo:FixedValue : epo:Numeric [0..1]
  epo:FixedValueType : epo:Code [0..1]
  epo:Formula : epo:Text [0..*]
  epo:hasAwardCriterionType : at-voc:award-criterion-type [0..1]
  epo:hasFixedValueType : at-voc:number-fixed [0..1]
  epo:hasThresholdType : at-voc:number-threshold [0..*]
  epo:hasWeightValueType : at-voc:number-weight [0..1]
  epo:ID : epo:Identifier [1..1]
  epo:isUsedToAward : epo:LotGroup [0..*]
  epo:isUsedToAward : epo:Lot [0..*]
  epo:ThresholdType : epo:Code [0..*]
  epo:ThresholdValue : epo:Numeric [0..1]
  epo:WeightValue : epo:Numeric [0..1]
  epo:WeightValueType : epo:Code [0..1]
  epo:WeigthingJustification : epo:Text [0..*]
}
class "epo:ReviewTerm" {
  epo:isAppliedBy : epo:Lot [0..1]
  epo:ReviewDeadline : epo:DateTime [0..1]
  epo:ReviewDeadlineInformation : epo:Text [0..*]
  epo:ReviewProcedure : epo:Text [0..*]
}
class "epo:ProcedureTerm" {
  epo:AdditionalInformationDeadline : epo:DateTime [0..1]
  epo:combineLotsInto : epo:LotGroup [0..*]
  epo:EstimatedTenderInvitationDate : epo:Date [0..1]
  epo:GroupLotEvaluationMethod : epo:Text [0..*]
  epo:hasClarificationsAvailableVia : epo:Channel [0..*]
  epo:hasQuestionsMadeAvailableVia  : epo:Channel [0..*]
  epo:LotAwardLimit : epo:Numeric [0..1]
  epo:ReceiptExpressionsDeadline : epo:DateTime [0..1]
}
class "epo:ProcurementCriterion" {
  epo:Description : epo:Text [0..*]
  epo:ID : epo:Identifier [1..1]
  epo:Name : epo:Text [0..*]
}
class "epo:Organisation" {
  epo:hasDefaultContactPoint : epo:ContactPoint [1..*]
  epo:hasLocation : epo:Location [0..*]
  epo:isMemberOf : epo:OrganisationGroup [0..*]
  epo:leadOf : epo:OrganisationGroup [0..*]
  epo:LegalFormType : epo:Code [0..1]
  epo:Name : epo:Text [0..*]
}
class "epo:Location" {
  epo:hasPostalAddress : epo:Address [0..1]
}
class "epo:ContractAwardNotice" {
  epo:hasTotalFrameworkValue : epo:Value [0..1]
  epo:hasTotalValue : epo:Value [0..1]
  epo:notifiesAwardResult : epo:AwardDecision [1]
  epo:summarisesProcedure : epo:Procedure [0..*]
}
class "epo:Value" {
  epo:CalculationMethod : epo:Text [0..*]
  epo:MaximumAmount : epo:Amount [0..1]
  epo:MinimumAmount : epo:Amount [0..1]
  epo:OverallAmount : epo:Amount [0..1]
  epo:VATIncludedIndicator : epo:Indicator [0..1]
  epo:VATPercentage : epo:Numeric [0..1]
}
class "epo:Address" {
  epo:AdditionalStreetName : epo:Text [0..*]
  epo:BlockName : epo:Text [0..*]
  epo:BuildingName : epo:Text [0..*]
  epo:BuildingNumber : epo:Text [0..*]
  epo:CityName : epo:Text [0..*]
  epo:CitySubdivisionName : epo:Text [0..*]
  epo:CountryCode : epo:Code [0..1]
  epo:CountryCode : epo:Code [1..1]
  epo:CountrySubentity : epo:Text [0..*]
  epo:CountrySubentityCode : epo:Code [0..1]
  epo:Department : epo:Text [0..*]
  epo:District : epo:Text [0..*]
  epo:Floor : epo:Text [0..*]
  epo:has : epo:LocationCoordinate [0..1]
  epo:hasCountryCode : at-voc:country [1]
  epo:hasCountryCode : at-voc:country [0..1]
  epo:hasCountrySubentityCode : at-voc:nuts [0..1]
  epo:ID : epo:Identifier [0..1]
  epo:InhouseMail : epo:Text [0..*]
  epo:MarkAttention : epo:Text [0..*]
  epo:MarkCare : epo:Text [0..*]
  epo:PlotIdentification : epo:Text [0..*]
  epo:PostalZone : epo:Text [0..*]
  epo:Postbox : epo:Text [0..*]
  epo:Region : epo:Text [0..*]
  epo:Room : epo:Text [0..*]
  epo:StreetName : epo:Text [0..*]
  epo:TimezoneOffset : epo:Text [0..*]
}
class "epo:Lot" {
  epo:AdditionalInformation : epo:Text [0..*]
  epo:applies : epo:MultipleStageProcedureTerm [0..1]
  epo:applies : epo:ContractTerm [0..1]
  epo:AwardDateScheduled : epo:Date [0..1]
  epo:contributesToImplement : epo:ProjectProcurement [1]
  epo:Description : epo:Text [0..*]
  epo:EstimatedTenderInvitationDate : epo:Date [0..1]
  epo:GPAUsage : epo:Indicator [0..1]
  epo:has : epo:Purpose [1]
  epo:has : epo:OpeningTerm [1]
  epo:hasAwardedEstimatedValue : epo:Value [0..1]
  epo:hasAwardedValue : epo:Value [0..1]
  epo:hasContractDuration : epo:Period [0..1]
  epo:hasEstimatedBuyerConcessionRevenue : epo:Value [0..1]
  epo:hasEstimatedUserConcessionRevenue : epo:Value [0..1]
  epo:hasEstimatedValue : epo:Value [0..1]
  epo:hasReservedProcurement : at-voc:reserved-procurement [0..*]
  epo:hasTenderEvaluationTerm : epo:EvaluationTerm [0..1]
  epo:hasVariantPermission : at-voc:permission [0..1]
  epo:ID : epo:Identifier [0..1]
  epo:involvesOverallStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:isAwardedTo : epo:TenderLot [0..*]
  epo:isFundedBy : epo:Fund [0..*]
  epo:isGroupedIn : epo:LotGroup [0..*]
  epo:isProvidedWithin : at-voc:requirement-stage [0..*]
  epo:isReferredToIn : epo:ProcurementDocument [1..*]
  epo:PerformingStafQualificationInformation : epo:Code [0..*]
  epo:providesAdditionalInformation : epo:StatisticalInformation [0..1]
  epo:refersTo : epo:PlannedProcurementPart [0..*]
  epo:refersTo : epo:Item [0..*]
  epo:requires : epo:SecurityClearanceTerm [0..*]
  epo:ReservedProcurement : epo:Code [0..*]
  epo:SMESuitable : epo:Indicator [0..1]
  epo:Title : epo:Text [0..*]
  epo:usesAdhoc : epo:Channel [0..*]
  epo:VariantsPermission : epo:Code [0..1]
}
class "epo:Role" {
  epo:Description : epo:Text [0..*]
  epo:has : epo:ContactPoint [0..*]
  epo:Title : epo:Text [0..*]
  reg2015:isInvolvedIn : epo:Procedure [0..*]
}
class "epo:ProcurementDocument" {
  epo:FreeEAccess : epo:Indicator [0..1]
}
class "epo:ProcurementServiceProvider" {
  epo:executesPayment : epo:Lot [0..*]
  epo:isGroupLeader : epo:Lot [0..*]
  epo:manages : epo:BuyerProfile [0..1]
  epo:processesRequestsToParticipate : epo:Lot [0..*]
  epo:processesTenders : epo:Lot [0..*]
  epo:providesAdditionalInformationAboutProcurementProcedure : epo:Lot [0..*]
  epo:providesOfflineAccessToProcurementDocuments : epo:Lot [0..*]
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  epo:receivesRequestsToParticipate : epo:Lot [0..*]
  epo:receivesTenders : epo:Lot [0..*]
  epo:signsContract : epo:Lot [0..*]
  epo:usesBudgetToPayContract : epo:Lot [0..*]
  reg2015:executesPayment : epo:Procedure [0..*]
  reg2015:isGroupLeader : epo:Procedure [0..*]
  reg2015:processesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:processesTenders : epo:Procedure [0..*]
  reg2015:providesAdditionalInformationAboutProcurementProcedure : epo:Procedure [0..*]
  reg2015:providesOfflineAccessToProcurementDocuments : epo:Procedure [0..*]
  reg2015:receivesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:receivesTenders : epo:Procedure [0..*]
  reg2015:signsContract : epo:Procedure [0..*]
  reg2015:usesBudgetToPayContract : epo:Procedure [0..*]
}
class "epo:StatisticalInformation" {
  epo:AbnormallyLowTenderLots : epo:Integer [0..1]
  epo:CleanVehicles : epo:Integer [0..1]
  epo:EEAReceivedTenderLots : epo:Integer [0..1]
  epo:ElectronicTenderLots : epo:Integer [0..1]
  epo:HighestReceivedTenderLotValues : epo:Amount [0..1]
  epo:InadmissibleTenderLots : epo:Integer [0..1]
  epo:LowestReceivedTenderLotValues : epo:Amount [0..1]
  epo:MediumTenderPerLots : epo:Integer [0..1]
  epo:NumberOfTenderersInvited : epo:Integer [0..1]
  epo:ReceivedMicroTenderLots : epo:Integer [0..1]
  epo:ReceivedNONEEATenderLots : epo:Integer [0..1]
  epo:ReceivedParticipationRequests : epo:Integer [0..1]
  epo:ReceivedReviewRequests : epo:Integer [0..1]
  epo:ReceivedSmallTenderLots : epo:Integer [0..1]
  epo:ReceivedSMETenderLots : epo:Integer [0..1]
  epo:ReceivedTenderLots : epo:Integer [1..1]
  epo:ReceivedTenderLots : epo:Integer [0..1]
  epo:TotalValueSubcontracted : epo:Integer [0..1]
  epo:TotalVehicles : epo:Integer [0..1]
  epo:UnverifiedTenderLots : epo:Integer [0..1]
  epo:ZeroEmissionVehicles : epo:Integer [0..1]
}
class "epo:PriorInformationNotice" {
  epo:EstimatedContractNoticePublicationDate : epo:Date [1..1]
  epo:EstimatedContractNoticePublicationDate : epo:Date [0..1]
  epo:notifies : epo:PlannedProcurementPart [0..*]
}
class "epo:Notice" {
  epo:DPSScope : epo:Code [0..1]
  epo:FormType : epo:Code [1..1]
  epo:hasDPSScope : at-voc:dps-usage [0..1]
  epo:hasFormType : at-voc:form-type [1]
  epo:hasNotificationPhasesType : epo:notification-phases-content-types [0..1]
  epo:NotificationContentType : epo:Code [0..1]
  epo:notifies : epo:Procedure [0..*]
  epo:PreferredPublicationDate : epo:Date [0..1]
  epo:PublicationDate : epo:Date [1..1]
  epo:relatesToNotice : epo:Notice [0..*]
}
class "epo:Procedure" {
  epo:Accelerated : epo:Indicator [0..1]
  epo:AcceleratedProcedureJustification : epo:Text [0..*]
  epo:ChoiceJustification : epo:Text [0..*]
  epo:CompetitionTermination : epo:Indicator [0..1]
  epo:Description : epo:Text [0..*]
  epo:DesignContest : epo:Indicator [0..1]
  epo:has : epo:ProcedureTerm [0..1]
  epo:has : epo:DirectAwardTerm [0..1]
  epo:hasEstimatedValue : epo:Value [1]
  epo:hasLegalBasis : at-voc:legal-basis [0..*]
  epo:hasLegalRegime : epo:legal-regime [0..*]
  epo:hasOverallPurpose : epo:Purpose [0..1]
  epo:hasProcedureType : at-voc:procurement-procedure-type [1]
  epo:hasTotalValue : epo:Value [1]
  epo:ID : epo:Identifier [1..1]
  epo:involvesOverallStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:isConcludedBy : epo:Contract [0..*]
  epo:isResponsiblityOf : epo:Buyer [1..*]
  epo:leadsTo : epo:Contract [1..*]
  epo:LegalBasis : epo:Code [0..1]
  epo:LegalBasis : epo:Code [0..*]
  epo:LegalBasisID : epo:URI [0..*]
  epo:LegalRegime : epo:Code [0..*]
  epo:LotMinimumSubmission : epo:Numeric [0..1]
  epo:LotSubmissionLimit : epo:Numeric [0..1]
  epo:MainFeature : epo:Text [0..*]
  epo:MaximumNumberOfLotsToBeAwarded : epo:Numeric [0..1]
  epo:ProcedureType : epo:Code [1..1]
  epo:specifies : epo:Lot [1..*]
  epo:Title : epo:Text [0..*]
  epo:uses : epo:ExclusionGround [0..*]
  epo:uses : epo:AccessTerm [0..*]
  reg2015:AdditionalInformation : epo:Text [0..*]
  reg2015:AwardedByCPB : epo:Code [0..1]
  reg2015:BuyerLegalType : epo:Code [0..1]
  reg2015:BuyerLegalTypeDescription : epo:Text [0..*]
  reg2015:BuyerMainActivity : epo:Code [0..1]
  reg2015:BuyerMainActivityDescription : epo:Text [0..*]
  reg2015:DeadlineTendersAndRequest : epo:DateTime [1..1]
  reg2015:EstimatedTenderAndRequestInvitationDate : epo:Date [0..1]
  reg2015:GPAUsage : epo:Indicator [0..1]
  reg2015:JointProcurement : epo:Indicator [0..1]
  reg2015:LanguagesTendersAndRequest : epo:Code [1..*]
  reg2015:LegalBasisDescription : epo:Text [0..*]
  reg2015:PerformingStaffQualificationInformation : epo:Indicator [0..1]
  reg2015:PublicationOfCallForCompetition : epo:Indicator [0..1]
  reg2015:VariantPermission : epo:Code [0..1]
  null : epo :Procurement Term 
  null : epo :Procedure 
  reg2015:applies : epo:FrameworkAgreementTerm [0..*]
  reg2015:applies : epo:ReviewTerm [0..*]
  reg2015:applies : epo:SelectionCriterion [0..*]
  reg2015:applies : epo:OpeningTerm [0..*]
  reg2015:applies : epo:ContractTerm [0..*]
  reg2015:applies : epo:SubmissionTerm [0..*]
  reg2015:has : epo:MultipleStageProcedureTerm [0..1]
  reg2015:hasBuyerLegalType : at-voc:buyer-legal-type [0..1]
  reg2015:hasCriteriaInProcurementDocument : epo:ProcurementCriterion [1..*]
  reg2015:hasFrameworkAgreementDuration : epo:Period [0..1]
  reg2015:hasReservedProcurement : at-voc:reserved-procurement [1..*]
  reg2015:isFundedBy : epo:Fund [0..*]
  reg2015:requires : epo:SecurityClearanceTerm [1..*]
  reg2015:uses : epo:Technique [0..*]
  reg2015:usesAdhoc : epo:Channel [0..*]
  reg2015:usesToAward : epo:AwardCriterion [0..*]
}
class "epo:Document" {
  epo:changeRefersToInstance : epo:Document [0..*]
  epo:DispatchDate : epo:Date [0..1]
  epo:hasChange : epo:Change [0..*]
  epo:hasNonPublishedElement : epo:PublicationProvision [0..*]
  epo:hasOfficialLanguage : at-voc:language [1..*]
  epo:hasRestrictedCommunicationJustification : at-voc:communication-justification [1]
  epo:hasUnofficialLanguage : at-voc:language [0..*]
  epo:ID : epo:Identifier [0..*]
  epo:includes : epo:RegulatoryFrameworkInformation [0..*]
  epo:IsMadeAvailableVia : epo:Channel [0..*]
  epo:isSubmittedBy : epo:Agent [0..1]
  epo:OfficialLanguage : epo:Code [0..*]
  epo:ReceptionDate : epo:Date [0..1]
  epo:refersToPrevious : epo:Document [0..*]
  epo:relatesTo : epo:Procedure [0..*]
  epo:RestrictedCommunicationsJustification : epo:Code [0..1]
  epo:UnofficialLanguage : epo:Code [0..*]
  epo:UUID : epo:Identifier [1..1]
}
class "epo:Buyer" {
  epo:ActivityDescription : epo:Text [0..*]
  epo:appoints : epo:EvaluationBoard [0..1]
  epo:BuyerLegalType : epo:Code [0..1]
  epo:BuyerLegalTypeDescription : epo:Text [0..*]
  epo:ContractingEntity : epo:Indicator [0..1]
  epo:executesPayment : epo:Lot [0..*]
  epo:has : epo:BuyerProfile [0..1]
  epo:hasBuyerLegalType : at-voc:buyer-legal-type [1]
  epo:hasMainActivityType : at-voc:main-activity [0..1]
  epo:isGroupLeader : epo:Lot [0..*]
  epo:MainActivityType : epo:Code [0..1]
  epo:makesDecsion : epo:AwardDecision [0..*]
  epo:plans : epo:PlannedProcurementPart [0..*]
  epo:processesRequestsToParticipate : epo:Lot [0..*]
  epo:processesTenders : epo:Lot [0..*]
  epo:providesAdditionalInformationAboutProcurementProcedure : epo:Lot [0..*]
  epo:providesOfflineAccessToProcurementDocuments : epo:Lot [0..*]
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  epo:receivesRequestsToParticipate : epo:Lot [0..*]
  epo:receivesTenders : epo:Lot [0..*]
  epo:signsContract : epo:Lot [0..*]
  epo:usesBudgetToPayContract : epo:Lot [0..*]
  reg2015:executesPayment : epo:Procedure [0..*]
  reg2015:isGroupLeader : epo:Procedure [0..*]
  reg2015:processesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:processesTenders : epo:Procedure [0..*]
  reg2015:providesAdditionalInformationAboutProcurementProcedure : epo:Procedure [0..*]
  reg2015:providesMoreInformationOnTimeLimitsForReviewProcedures : epo:Procedure [0..*]
  reg2015:providesOfflineAccessToProcurementDocuments : epo:Procedure [0..*]
  reg2015:receivesRequestsToParticipate : epo:Procedure [0..*]
  reg2015:receivesTenders : epo:Procedure [0..*]
  reg2015:signsContract : epo:Procedure [0..*]
  reg2015:usesBudgetToPayContract : epo:Procedure [0..*]
}
class "epo:ProjectProcurement" {
  epo:accessMarketThrough : epo:Procedure [0..*]
  epo:Description : epo:Text [0..*]
  epo:foreseesPlannedProcurementPart : epo:PlannedProcurementPart [0..*]
  epo:ID : epo:Identifier [1..1]
  epo:Title : epo:Text [0..*]
}
class "epo:CentralPurchasingBody" {
  epo:CPBType : epo:Code [0..1]
  epo:hasCentralPurchasingBodyType : epo:cpb-type [0..1]
}
class "epo:Purpose" {
  epo:AdditionalClassification : epo:Code [0..*]
  epo:AdditionalContractNature : epo:Code [0..*]
  epo:ContractNatureType : epo:Code [1..1]
  epo:ContractNatureType : epo:Code [0..1]
  epo:hasAdditionalClassification : at-voc:cpv [0..*]
  epo:hasAdditionalContractNature : at-voc:contract-nature [0..*]
  epo:hasContractNature : at-voc:contract-nature [1]
  epo:hasContractNatureType : at-voc:contract-nature [0..1]
  epo:hasMainClassification : at-voc:cpv [1]
  epo:hasMainClassification : at-voc:cpv [1..*]
  epo:hasOptionsPermission : at-voc:permission [0..1]
  epo:MainClassification : epo:Code [1..1]
  epo:MainClassification : epo:Code [0..1]
  epo:OptionsDescription : epo:Text [0..*]
  epo:OptionsPermission : epo:Code [0..1]
  epo:TotalMagnitudeQuantity : epo:Quantity [0..1]
}
class "epo:Agent" {
  epo:Alias : epo:Text [0..*]
  epo:delegatesAncillaryActivitiesOn : epo:Agent [0..*]
  epo:ID : epo:Identifier [0..*]
  epo:isCreatorOf : epo:Document [1..*]
  epo:playsRole : epo:Role [0..*]
  epo:provides : epo:RegulatoryFrameworkInformation [0..*]
}
class "epo:ContractNotice" {
  epo:Recurrence : epo:Indicator [0..1]
  epo:RecurrenceDescription : epo:Text [0..*]
  epo:RecurrenceDescription : epo:Text [0..1]
}
class "epo:PublicationProvision" {
  epo:AvailabilityDate : epo:Date [0..1]
  epo:hasNonPublicationJustification : at-voc:non-publication-justification [0..1]
  epo:hasNonPublishedElement : epo:ResourceElement [0..*]
  epo:NonPublicationJustification : epo:Code [0..1]
  epo:NonPublicationJustificationDescription : epo:Text [0..*]
}
class "epo:PublicOrganisation" {
  null : epo:Agent 
}
class "epo:PurchaseContract" {
  epo:hasRulesSetBy : epo:FrameworkAgreement [0..1]
}
class "epo:ProcurementCriterion" {
  epo:Description : epo:Text [0..*]
  epo:ID : epo:Identifier [1..1]
  epo:Name : epo:Text [0..*]
}
class "epo:SecurityClearanceTerm" {
  epo:appliesTo : org:Site [1..*]
  epo:appliesTo : epo:Winner [1..*]
  epo:appliesTo : epo:Document [1..*]
  epo:Deadline : epo:DateTime [0..1]
  epo:Description : epo:Text [0..*]
}
class "epo:FrameworkAgreementTerm" {
  epo:appliesTo : epo:Lot [1..*]
  epo:BuyerCoverage : epo:Text [0..*]
  epo:DurationExtensionJustification : epo:Text [0..*]
  epo:FrameworkAgreementType : epo:Code [1..1]
  epo:hasFrameworkAgreementType : at-voc:framework-agreement [1]
  epo:hasOverallMaximumValue : epo:Value [0..1]
  epo:isUsedBy : epo:LotGroup [0..*]
  epo:MaximumNumberOfAwardedTenderers : epo:Quantity [0..1]
}
class "epo:Purpose" {
  epo:AdditionalClassification : epo:Code [0..*]
  epo:AdditionalContractNature : epo:Code [0..*]
  epo:ContractNatureType : epo:Code [1..1]
  epo:ContractNatureType : epo:Code [0..1]
  epo:hasAdditionalClassification : at-voc:cpv [0..*]
  epo:hasAdditionalContractNature : at-voc:contract-nature [0..*]
  epo:hasContractNature : at-voc:contract-nature [1]
  epo:hasContractNatureType : at-voc:contract-nature [0..1]
  epo:hasMainClassification : at-voc:cpv [1]
  epo:hasMainClassification : at-voc:cpv [1..*]
  epo:hasOptionsPermission : at-voc:permission [0..1]
  epo:MainClassification : epo:Code [1..1]
  epo:MainClassification : epo:Code [0..1]
  epo:OptionsDescription : epo:Text [0..*]
  epo:OptionsPermission : epo:Code [0..1]
  epo:TotalMagnitudeQuantity : epo:Quantity [0..1]
}
class "epo:RegulatoryFrameworkInformation" {
  epo:hasRegulatoryFrameworkProvider : epo:regulatory-framework-provider [1..*]
  epo:RegulatoryFrameworkProvider : epo:Code [1..*]
}
class "epo:ResourceElement" {
  epo:Description : epo:Text [0..*]
  epo:ElementIRI : epo:URI [1..1]
}
class "epo:Reviewer" {
  epo:providiesMoreInformationOnTimeLimitsForReviewProcedures : epo:Lot [0..*]
  reg2015:providesMoreInformationOnTimeLimitsForReviewProcedures : epo:Procedure [0..*]
}
class "epo:ReviewTerm" {
  epo:isAppliedBy : epo:Lot [0..1]
  epo:ReviewDeadline : epo:DateTime [0..1]
  epo:ReviewDeadlineInformation : epo:Text [0..*]
  epo:ReviewProcedure : epo:Text [0..*]
}
class "epo:Role" {
  epo:Description : epo:Text [0..*]
  epo:has : epo:ContactPoint [0..*]
  epo:Title : epo:Text [0..*]
  reg2015:isInvolvedIn : epo:Procedure [0..*]
}
class "epo:SecurityClearanceTerm" {
  epo:appliesTo : org:Site [1..*]
  epo:appliesTo : epo:Winner [1..*]
  epo:appliesTo : epo:Document [1..*]
  epo:Deadline : epo:DateTime [0..1]
  epo:Description : epo:Text [0..*]
}
class "epo:SelectionCriterion" {
  epo:appliesTo : epo:LotGroup [0..*]
  epo:Formula : epo:Text [0..*]
  epo:hasSelectionCriterionType : at-voc:selection-criterion [0..1]
  epo:hasThresholdType : at-voc:number-threshold [0..*]
  epo:hasWeightValueType : at-voc:number-weight [0..*]
  epo:isAppliedBy : epo:Lot [0..*]
  epo:SelectionCriterionType : epo:Code [0..1]
  epo:ThresholdType : epo:Code [0..*]
  epo:ThresholdValue : epo:Numeric [1..1]
  epo:UsedForCandidateRestriction : epo:Indicator [0..1]
  epo:usedForReductionOfCandidates : epo:Lot [0..*]
  epo:WeightingJustification : epo:Text [0..*]
  epo:WeightValue : epo:Numeric [1..1]
  epo:WeightValueType : epo:Code [0..*]
}
class "epo:SocialProcurement" {
  epo:fulfillsRequirement : at-voc:social-objective [1..*]
  epo:FulfillsRequirement : epo:Code [1..*]
}
class "epo:StatisticalInformation" {
  epo:AbnormallyLowTenderLots : epo:Integer [0..1]
  epo:CleanVehicles : epo:Integer [0..1]
  epo:EEAReceivedTenderLots : epo:Integer [0..1]
  epo:ElectronicTenderLots : epo:Integer [0..1]
  epo:HighestReceivedTenderLotValues : epo:Amount [0..1]
  epo:InadmissibleTenderLots : epo:Integer [0..1]
  epo:LowestReceivedTenderLotValues : epo:Amount [0..1]
  epo:MediumTenderPerLots : epo:Integer [0..1]
  epo:NumberOfTenderersInvited : epo:Integer [0..1]
  epo:ReceivedMicroTenderLots : epo:Integer [0..1]
  epo:ReceivedNONEEATenderLots : epo:Integer [0..1]
  epo:ReceivedParticipationRequests : epo:Integer [0..1]
  epo:ReceivedReviewRequests : epo:Integer [0..1]
  epo:ReceivedSmallTenderLots : epo:Integer [0..1]
  epo:ReceivedSMETenderLots : epo:Integer [0..1]
  epo:ReceivedTenderLots : epo:Integer [1..1]
  epo:ReceivedTenderLots : epo:Integer [0..1]
  epo:TotalValueSubcontracted : epo:Integer [0..1]
  epo:TotalVehicles : epo:Integer [0..1]
  epo:UnverifiedTenderLots : epo:Integer [0..1]
  epo:ZeroEmissionVehicles : epo:Integer [0..1]
}
class "epo:StrategicProcurement" {
  epo:isSpecifiedIn : epo:ResourceElement [0..*]
  epo:StrategicProcurementDescription : epo:Text [0..*]
}
class "epo:Subcontract" {
  epo:acceptsProposalOf : epo:AwardDecision [0..1]
  epo:Description : epo:Text [0..*]
  epo:EstimatedShare : epo:Numeric [0..1]
  epo:hasEstimatedValue : epo:Value [0..1]
  epo:isReferredToIn : epo:AwardDecision [1..*]
  epo:proposesSubcontractor : epo:Subcontractor [0..*]
  epo:refersToAwardResult : epo:AwardDecision [1..*]
}
class "epo:Subcontractor" {

}
class "epo:SubcontractTerm" {
  epo:Description : epo:Text [0..*]
  epo:hasSubcontractingObligation : at-voc:subcontracting-obligation [0..*]
  epo:MaximumShare : epo:Numeric [0..1]
  epo:MinimumShare : epo:Numeric [0..1]
  epo:MinimumShareSubjectMatter : epo:Text [0..*]
  epo:MinimumSubcontractorsProposedObligation : epo:Indicator [0..1]
  epo:SubcontractingInvolved : epo:Indicator [0..1]
  epo:SubcontractingObligation : epo:Code [0..*]
  epo:SubcontractorsProposedAboveObligation : epo:Indicator [0..1]
}
class "epo:SubmissionTerm" {
  epo:AdvancedElectronicSignatureRequired : epo:Indicator [0..1]
  epo:ECataloguePermission : epo:Code [0..1]
  epo:ESubmissionPermission : epo:Code [0..1]
  epo:GuaranteeDescription : epo:Text [0..*]
  epo:GuaranteeRequired : epo:Indicator [0..1]
  epo:hasECataloguePermission : at-voc:permission [0..1]
  epo:hasESubmissionPermission : at-voc:permission [0..1]
  epo:hasLanguage : at-voc:language [0..*]
  epo:hasLateSubmissionPermission : at-voc:missing-info-submission [0..1]
  epo:hasNonElectronicSubmissionJustification : at-voc:communication-justification [0..*]
  epo:hasSubmissionCommunicationMeans : epo:Channel [0..*]
  epo:hasTenderSubcontractingInformation : at-voc:subcontracting-indication [0..*]
  epo:hasValidityPeriod : epo:Period [0..1]
  epo:isAppliedBy : epo:Lot [1..*]
  epo:Language : epo:Code [0..*]
  epo:LateSubmissionInformationDescription : epo:Text [0..*]
  epo:LateSubmissionPermission : epo:Code [0..1]
  epo:MultipleTenderSubmissionAllowed : epo:Indicator [0..1]
  epo:NonElectronicSubmissionDescription : epo:Text [0..*]
  epo:NonElectronicSubmissionJustification : epo:Code [0..*]
  epo:ReceiptDeadline : epo:DateTime [1..1]
  epo:TenderSubcontractingInformation : epo:Code [0..*]
}
class "epo:System" {
  epo:Description : epo:Text [0..*]
  epo:isOwnedBy : epo:Agent [0..1]
  epo:Name : epo:Text [0..*]
}
class "epo:TechnicalSpecification" {
  epo:AccessibilityCriterion : epo:Code [0..*]
  epo:includesAccessibilityCriterion : at-voc:accessibility [0..*]
  epo:NonAccessibilityCriterionJustification : epo:Text [0..*]
}
class "epo:Technique" {
  epo:Description : epo:Text [0..*]
  epo:hasValidityPeriod : epo:Period [0..1]
  epo:ID : epo:Identifier [0..1]
  epo:isAvailableVia : epo:Channel [0..*]
  epo:isUsedBy : epo:Lot [1..*]
}
class "epo:Tender" {
  epo:attaches : epo:TenderDocument [1..*]
  epo:ElectronicSubmission : epo:Indicator [0..1]
  epo:hasSubmissionTerm : epo:SubmissionTerm [1]
  epo:ID : epo:Identifier [1..1]
  epo:includes : epo:TenderLot [1..*]
  epo:specifiesSubcontractors : epo:EconomicOperator [0..*]
}
class "epo:Tenderer" {
  epo:submits : epo:Tender [1..*]
  epo:substantiates : epo:ExclusionGround [1..*]
  epo:withdraws : epo:Tender [0..*]
}
class "epo:TenderLot" {
  epo:appliesTo : epo:LotGroup [0..1]
  epo:hasFinancialOfferValue : epo:Value [1..*]
  epo:ID : epo:Identifier [1..1]
  epo:proposes : epo:Subcontract [0..*]
  epo:refersTo : epo:Item [0..*]
  epo:relatesTo : epo:Lot [0..*]
  epo:Variant : epo:Indicator [0..1]
}
class "epo:TenderLotEvaluationRank" {
  epo:RankingInFirstStage : epo:Numeric [0..1]
  epo:ranks : epo:TenderLot [1..*]
  epo:TenderLotRank : epo:Numeric [0..1]
}
class "epo:Value" {
  epo:CalculationMethod : epo:Text [0..*]
  epo:MaximumAmount : epo:Amount [0..1]
  epo:MinimumAmount : epo:Amount [0..1]
  epo:OverallAmount : epo:Amount [0..1]
  epo:VATIncludedIndicator : epo:Indicator [0..1]
  epo:VATPercentage : epo:Numeric [0..1]
}
class "epo:VoluntaryEx-anteTransparencyNotice" {

}
class "epo:Winner" {
  epo:isRoleOfBusiness : epo:Business [0..*]
}
class "epo:cpb-type" {
  cpb-acq : skos:Concept [1..1]
  cpb-awa : skos:Concept [1..1]
}
class "epo:evaluation-group-type" {
  JURY : null [1..1]
  REGULAR_BOARD : null [1..1]
}
class "epo:legal-regime" {
  design-contest : skos:Concept [1..1]
  light-regime : skos:Concept [1..1]
  standard : skos:Concept [1..1]
}
class "epo:notification-phases-content-types" {
  COMPETITION.CN : skos:Concept [1..1]
  COMPETITION.PIN : skos:Concept [1..1]
  COMPETITION.QS : skos:Concept [1..1]
  CONTRACT.CM : skos:Concept [1..1]
  DAP.VEAT : skos:Concept [1..1]
  PLANNING.PIN : skos:Concept [1..1]
  RESULT.CAN : skos:Concept [1..1]
}
class "epo:regulatory-framework-provider" {
  info-emp : skos:Concept [1..1]
  info-envir : skos:Concept [1..1]
  info-tax : skos:Concept [1..1]
}
class "epo:Amount" {
  epo:AmountValue : epo:Numeric [1..1]
  epo:CurrencyID : epo:Code [1..1]
  epo:hasCurrency : at-voc:currency [1]
  epo:UnitCodeListAgencyID : epo:Text [0..*]
  epo:UnitCodeListAgencyName : epo:Text [0..*]
  epo:UnitCodeListID : epo:Text [0..*]
}
class "epo:Identifier" {
  epo:IdentifierValue : epo:Text [1..1]
  epo:SchemeAgencyID : epo:Text [0..*]
  epo:SchemeAgencyName : epo:Text [0..*]
  epo:SchemeDataURI : epo:URI [0..1]
  epo:SchemeID : epo:Text [0..*]
  epo:SchemeName : epo:Text [0..*]
  epo:SchemeURI : epo:URI [0..1]
  epo:SchemeVersionID : epo:Text [0..*]
}
class "epo:Measure" {
  epo:hasUnitCode : at-voc:measurement-unit [1]
  epo:MeasureValue : epo:Numeric [1..1]
  epo:UnitCode : epo:Code [1..1]
  epo:UnitCodeListAgencyID : epo:Text [0..*]
  epo:UnitCodeListAgencyName : epo:Text [0..*]
  epo:UnitCodeListID : epo:Text [0..*]
}
class "epo:Quantity" {
  epo:QuantityValue : epo:Numeric [1..1]
  epo:UnitDescription : epo:Text [0..*]
}
"epo:Agent" <|-- "epo:Organisation"
"epo:Agent" <|-- "epo:Person"
"epo:Agent" <|-- "epo:System"
"epo:Buyer" <|-- "epo:CentralPurchasingBody"
"epo:Contract" <|-- "epo:FrameworkAgreement"
"epo:Contract" <|-- "epo:PurchaseContract"
"epo:Document" <|-- "epo:Contract"
"epo:Document" <|-- "epo:Notice"
"epo:Document" <|-- "epo:ProcurementDocument"
"epo:Document" <|-- "epo:TenderDocument"
"epo:EconomicOperator" <|-- "epo:Subcontractor"
"epo:EconomicOperator" <|-- "epo:Tenderer"
"epo:Notice" <|-- "epo:BuyerProfileNotice"
"epo:Notice" <|-- "epo:CallForExpressionOfInterest"
"epo:Notice" <|-- "epo:ContractAwardNotice"
"epo:Notice" <|-- "epo:ContractModificationNotice"
"epo:Notice" <|-- "epo:ContractNotice"
"epo:Notice" <|-- "epo:PriorInformationNotice"
"epo:Notice" <|-- "epo:VoluntaryEx-anteTransparencyNotice"
"epo:Organisation" <|-- "epo:Business"
"epo:Organisation" <|-- "epo:OrganisationGroup"
"epo:Organisation" <|-- "epo:PublicOrganisation"
"epo:ProcurementCriterion" <|-- "epo:AwardCriterion"
"epo:ProcurementCriterion" <|-- "epo:ExclusionGround"
"epo:ProcurementCriterion" <|-- "epo:SelectionCriterion"
"epo:ProcurementDocument" <|-- "epo:CallForCompetition"
"epo:ProcurementDocument" <|-- "epo:TechnicalSpecification"
"epo:Role" <|-- "epo:Buyer"
"epo:Role" <|-- "epo:EconomicOperator"
"epo:Role" <|-- "epo:Mediator"
"epo:Role" <|-- "epo:ProcurementServiceProvider"
"epo:Role" <|-- "epo:Reviewer"
"epo:StrategicProcurement" <|-- "epo:GreenProcurement"
"epo:StrategicProcurement" <|-- "epo:InnovativeProcurement"
"epo:StrategicProcurement" <|-- "epo:SocialProcurement"
"epo:Technique" <|-- "epo:DynamicPurchaseSystemTechnique"
"epo:Technique" <|-- "epo:EAuctionTechnique"
"epo:Technique" <|-- "epo:FrameworkAgreementTechnique"
"epo:TenderDocument" <|-- "epo:ExpressionOfInterest"
"epo:TenderDocument" <|-- "epo:RequestForClarification"
"epo:TenderDocument" <|-- "epo:RequestForParticipation"
"epo:Tenderer" <|-- "epo:Winner"
"epo:Winner" <|-- "epo:Contractor"
@enduml
