
@startuml
class "epo:RequestForClarification" {

}
class "epo:ExpressionOfInterest" {

}
class "epo:RequestForParticipation" {

}
class "epo:Estimate" {

}
class "epo:SubcontractingEstimate" {
  dct:description : rdf:PlainLiteral [0..*]
  epo:hasEstimatedPercentage : xsd:decimal [0..1]
  epo:hasSubcontractingEstimatedValue : epo:MonetaryValue [0..1]
  epo:hasSubjectMatter : rdf:PlainLiteral [0..*]
}
class "epo:ConcessionEstimate" {
  epo:hasCalculationMethod : rdf:PlainLiteral [0..1]
  epo:hasConcessionEstimatedValue : epo:MonetaryValue [0..1]
  epo:hasEstimatedBuyerConcessionRevenue : epo:MonetaryValue [0..1]
  epo:hasEstimatedUserConcessionRevenue : epo:MonetaryValue [0..1]
}
class "epo:AwardOutcome" {
  epo:comprisesTenderAwardOutcome : epo:TenderAwardOutcome [0..*]
  epo:hasAwardedValue : epo:MonetaryValue [0..1]
  epo:hasAwardStatus : at-voc:winner-selection-status [0..1]
  epo:hasBargainPrice : epo:MonetaryValue [0..1]
  epo:hasNonAwardJustification : at-voc:non-award-justification [0..1]
}
class "epo:AccessTerm" {
  epo:definesCatalogueProvider : epo:CatalogueProvider [0..*]
  epo:definesCatalogueReceiver : epo:CatalogueReceiver [0..*]
  epo:definesOfflineAccessProvider : epo:OfflineAccessProvider [0..1]
  epo:definesProcurementProcedureInformationProvider : epo:ProcurementProcedureInformationProvider [0..1]
  epo:hasAdditionalInformationDeadline : xsd:dateTime [0..1]
  epo:hasDocumentRestrictionJustification : at-voc:communication-justification [0..1]
  epo:hasPublicAccessURL : xsd:anyURI [0..1]
  epo:hasRestrictedAccessURL : xsd:anyURI [0..1]
  epo:involvesProcurementDocument : epo:ProcurementDocument [0..1]
  epo:isProcurementDocumentRestricted : xsd:boolean [0..1]
  epo:refersToPlannedPart : epo:PlannedProcurementPart [0..*]
}
class "epo:AwardCriterion" {
  epo:hasAwardCriteriaStatedInProcurementDocuments : xsd:boolean [1..1]
  epo:hasAwardCriterionType : at-voc:award-criterion-type [0..1]
  epo:hasFixedValue : xsd:decimal [0..1]
  epo:hasFixedValueType : at-voc:number-fixed [0..1]
}
class "epo:AwardDecision" {
  epo:comprisesAwardOutcome : epo:AwardOutcome [0..*]
  epo:hasAdditionalNonAwardJustification : rdf:PlainLiteral [0..1]
  epo:hasAwardDecisionDate : xsd:dateTime [0..1]
}
class "epo:Business" {
  epo:hasBeneficialOwner : person:Person [0..*]
  epo:hasBusinessSize : at-voc:economic-operator-size [0..1]
  epo:isListedCompany : xsd:boolean [0..1]
}
class "epo:Buyer" {
  epo:delegatesAncillaryActivitiesTo : epo:ProcurementServiceProvider [0..*]
  epo:exposesInvoiceeChannel : cv:Channel [0..*]
  epo:hasActivityDescription : rdf:PlainLiteral [0..*]
  epo:hasBuyerProfile : xsd:anyURI [0..1]
  epo:indicatesInvoiceeContactPoint : cpov:ContactPoint 
  epo:isContractingEntity : xsd:boolean [0..1]
  epo:signsAwardDecision : epo:AwardDecision [0..*]
}
class "epo:LotSpecificTerm" {

}
class "epo:CentralPurchasingBody" {

}
class "epo:Contract" {
  epo-ord:hasTaxInformation : epo-ord:TaxInformation [0..1]
  epo:bindsBuyer : epo:Buyer [0..*]
  epo:bindsContractor : epo:Contractor [0..*]
  epo:hasContractConclusionDate : xsd:date [0..1]
  epo:hasContractValue : epo:MonetaryValue [0..1]
  epo:hasEntryIntoForceDate : xsd:date [0..1]
  epo:hasEstimatedDuration : epo:Duration [0..1]
  epo:hasLotReference : epo:Lot [1..*]
  epo:hasPurpose : epo:Purpose [0..1]
  epo:includesTender : epo:Tender [0..*]
  epo:isFundedBy : epo:Fund [0..*]
  epo:isSubjectToContractSpecificTerm : epo:ContractSpecificTerm [0..*]
  epo:signedByBuyer : epo:Buyer [0..*]
  epo:signedByContractor : epo:Contractor [0..*]
  epo:specifiesDeliverable : epo-con:Deliverable [0..*]
}
class "epo:Contractor" {
  epo:needsToBeAWinner : epo:Winner [0..1]
}
class "epo:ContractTerm" {
  epo:definesContractDuration : epo:Duration [0..1]
  epo:definesContractPeriod : epo:Period [0..1]
  epo:definesPaymentExecutor : epo:PaymentExecutor [0..1]
  epo:definesSpecificPlaceOfPerformance : dct:Location [0..*]
  epo:definesSubcontractingTerm : epo:SubcontractTerm [0..1]
  epo:hasAdditionalContractNature : at-voc:contract-nature [0..*]
  epo:hasBroadPlaceOfPerformance : at-voc:other-place-service [0..1]
  epo:hasContractNatureType : at-voc:contract-nature [0..1]
  epo:hasEInvoicing : xsd:boolean [0..1]
  epo:hasEInvoicingPermission : at-voc:permission [0..1]
  epo:hasEOrdering : xsd:boolean [0..1]
  epo:hasEPayment : xsd:boolean [0..1]
  epo:hasLegalFormRequirement : rdf:PlainLiteral [0..1]
  epo:hasMaximumNumberOfRenewals : xsd:integer [0..1]
  epo:hasOptions : xsd:boolean [0..1]
  epo:hasOptionsDescription : rdf:PlainLiteral [0..*]
  epo:hasPaymentArrangement : rdf:PlainLiteral [0..*]
  epo:hasPerformanceConditions : rdf:PlainLiteral [0..*]
  epo:hasPlaceOfPerformanceAdditionalInformation : rdf:PlainLiteral [0..*]
  epo:hasRenewalDescription : rdf:PlainLiteral [0..*]
  epo:hasReservedExecution : at-voc:applicability [0..1]
  epo:isRenewalIndicator : xsd:boolean [0..1]
}
class "epo:DesignContestRegimeTerm" {
  epo:definesPrize : epo:Prize [0..*]
  epo:hasDescriptionOfPrizes : rdf:PlainLiteral [0..1]
  epo:hasFollowupContract : xsd:boolean [0..1]
  epo:hasFollowupContractInformation : rdf:PlainLiteral [0..*]
  epo:hasParticipationPayment : rdf:PlainLiteral [0..1]
  epo:isJuryDecisionBinding : xsd:boolean [0..1]
}
class "epo:DirectAwardTerm" {
  epo:hasDirectAwardJustification : at-voc:direct-award-justification [0..1]
  epo:hasJustification : rdf:PlainLiteral [0..*]
  epo:refersToPreviousProcedure : epo:Procedure [0..1]
  epo:refersToPreviousProcedureLot : epo:Lot [0..*]
}
class "epo:Document" {
  adms:identifier : adms:Identifier [0..*]
  dct:description : rdf:PlainLiteral [0..1]
  dct:issued : xsd:dateTime [0..1]
  dct:title : rdf:PlainLiteral [0..1]
  epo:associatedWith : epo:Document [0..*]
  epo:hasAccessURL : xsd:anyURI [0..*]
  epo:hasDispatchDate : xsd:dateTime [0..1]
  epo:hasElectronicDigest : epo:Document [0..*]
  epo:hasElectronicSignature : epo:ElectronicSignature [0..*]
  epo:hasOfficialLanguage : at-voc:language [1..*]
  epo:hasPublicationDate : xsd:date [0..1]
  epo:hasReceptionDate : xsd:date [0..1]
  epo:hasUnofficialLanguage : at-voc:language [0..*]
  epo:hasUUID : adms:Identifier [0..1]
  epo:hasVersion : rdf:PlainLiteral [0..1]
  epo:refersToPrevious : epo:Document [0..*]
}
class "epo:DynamicPurchaseSystemTechnique" {
  epo:hasDPSScope : at-voc:dps-usage [0..1]
}
class "epo:EAuctionTechnique" {

}
class "epo:OfferingParty" {

}
class "epo:AcquiringCentralPurchasingBody" {

}
class "epo:ReviewRequester" {

}
class "epo:EvaluationTerm" {

}
class "epo:ExclusionGround" {

}
class "epo:FrameworkAgreement" {
  epo:resultsFromLotAwardOutcome : epo:LotAwardOutcome [0..*]
}
class "epo:FrameworkAgreementTechnique" {

}
class "epo:FrameworkAgreementTerm" {
  epo:hasBuyerCategoryDescription : rdf:PlainLiteral [0..*]
  epo:hasDurationExtensionJustification : rdf:PlainLiteral [0..1]
  epo:hasFrameworkAgreementType : at-voc:framework-agreement [1]
  epo:hasMaximumParticipantsNumber : xsd:integer [0..1]
}
class "epo:Fund" {
  adms:identifier : adms:Identifier [0..1]
  dct:description : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  epo:hasFundProgramme : at-voc:EU-programme [0..1]
  epo:hasURL : xsd:anyURI [0..1]
}
class "epo:CatalogueReceiver" {

}
class "epo:CatalogueProvider" {

}
class "epo:AwardingCentralPurchasingBody" {

}
class "epo:ContractLotCompletionInformation" {
  epo:describesLotCompletion : epo:Lot [1]
  epo:hasPaymentValueDiscrepancyJustification : rdf:PlainLiteral [0..1]
  epo:providesContractTotalPaymentValue : epo:MonetaryValue [0..1]
  epo:providesContractTotalPenaltyValue : epo:MonetaryValue [0..1]
  epo:refersToContract : epo:Contract [1]
}
class "epo:GreenProcurement" {
  epo:fulfillsRequirement : at-voc:green-public-procurement-criteria [0..*]
  epo:fulfillsRequirement : at-voc:environmental-impact [0..*]
  epo:usesCleanVehicleDirective : xsd:boolean [0..1]
}
class "epo:InnovativeProcurement" {
  epo:fulfillsRequirement : at-voc:innovative-acquisition [0..*]
}
class "epo:Lot" {
  epo:isSubjectToLotSpecificTerm : epo:LotSpecificTerm [0..*]
  epo:specifiesProcurementCriterion : epo:ProcurementCriterion [0..*]
}
class "epo:LotGroup" {
  adms:identifier : adms:Identifier [0..1]
  dct:description : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  epo:hasEstimatedValue : epo:MonetaryValue [0..1]
  epo:hasInternalIdentifier : adms:Identifier [0..*]
  epo:hasLaunchFrameworkAgreementMaximumValue : epo:MonetaryValue [0..1]
  epo:setsGroupingContextForLot : epo:Lot [1..*]
  epo:specifiesProcurementCriterion : epo:ProcurementCriterion [0..*]
}
class "epo:Mediator" {

}
class "epo:MultipleStageProcedureTerm" {
  epo:hasEstimatedInvitationToExpressInterestDate : xsd:date [0..1]
  epo:hasEstimatedInvitationToTenderDate : xsd:date [0..1]
  epo:hasMaximumNumberOfCandidates : xsd:integer [0..1]
  epo:hasMinimumNumberOfCandidates : xsd:integer [0..1]
  epo:hasNoNegotiationNecessary : xsd:boolean [0..1]
  epo:hasQualificationSystemDuration : epo:Duration [0..1]
  epo:hasQualificationSystemRenewalDescription : rdf:PlainLiteral [0..1]
  epo:hasSuccessiveReduction : xsd:boolean [0..1]
}
class "epo:Notice" {
  epo:conformsToLegalBasis : at-voc:legal-basis [0..*]
  epo:hasAdditionalInformation : rdf:PlainLiteral [0..1]
  epo:hasEFormsSubtype : xsd:integer [0..1]
  epo:hasESenderDispatchDate : xsd:dateTime [0..1]
  epo:hasFormNumber : rdf:PlainLiteral [0..1]
  epo:hasFormType : at-voc:form-type [0..1]
  epo:hasNoticePublicationNumber : rdf:PlainLiteral [0..1]
  epo:hasNoticeType : at-voc:notice-type [1]
  epo:hasOJSIssueNumber : xsd:integer [0..1]
  epo:hasOJSType : rdf:PlainLiteral [0..1]
  epo:isBasedOnImplementingRegulation : at-voc:legal-basis [0..1]
  epo:refersToLot : epo:Lot [1..*]
  epo:refersToNotice : epo:Notice [0..1]
  epo:refersToProcedure : epo:Procedure [1]
}
class "epo:OpeningTerm" {
  epo:definesOpeningPlace : locn:Address [0..1]
  epo:hasOpeningDateTime : xsd:dateTime [1..1]
  epo:hasOpeningDescription : rdf:PlainLiteral [0..*]
  epo:hasOpeningURL : xsd:anyURI [0..1]
}
class "epo:OrganisationGroup" {
  epo:hasGroupType : rdf:PlainLiteral [0..*]
  epo:hasMember : org:Organization [1..*]
  epo:leadBy : org:Organization [0..1]
}
class "epo:VehicleInformation" {
  epo:concernsGreenProcurement : epo:GreenProcurement [1]
  epo:hasCleanVehicles : xsd:integer [0..1]
  epo:hasTotalVehicles : xsd:integer [0..1]
  epo:hasZeroEmissionVehicles : xsd:integer [0..1]
  epo:specifiesCleanVehicleDirectiveContractType : at-voc:cvd-contract-type [0..1]
  epo:specifiesCleanVehicleDirectiveVehicleCategory : at-voc:vehicle-category [0..1]
}
class "epo:NonPublishedInformation" {
  epo:concernsNotice : epo:Notice [1]
  epo:hasAccessibilityDate : xsd:date [0..1]
  epo:hasConfidentialityJustification : rdf:PlainLiteral [0..1]
  epo:hasNonPublicationJustification : at-voc:non-publication-justification [1]
  epo:relatesToEFormSectionIdentifier : adms:Identifier [1..*]
}
class "epo:Period" {
  epo:hasBeginning : xsd:dateTime [0..1]
  epo:hasEnd : xsd:dateTime [0..1]
  epo:hasTimePeriod : at-voc:timeperiod [1..*]
}
class "epo:PlannedProcurementPart" {
  epo:foreseesProcurementObject : epo:ProcurementObject [0..1]
  epo:foreseesTechnique : epo:Technique [0..*]
  epo:hasPlannedDuration : epo:Duration [0..1]
  epo:hasPlannedPeriod : epo:Period [0..1]
}
class "epo:SelectionEvaluationTerm" {

}
class "epo:AwardEvaluationTerm" {
  epo:hasAwardCriteriaEvaluationFormula : rdf:PlainLiteral [0..*]
  epo:hasAwardCriteriaOrderJustification : rdf:PlainLiteral [0..1]
  epo:hasOverallCostAwardCriteriaPonderation : xsd:decimal [0..1]
  epo:hasOverallPriceAwardCriteriaPonderation : xsd:decimal [0..1]
  epo:hasOverallQualityAwardCriteriaPonderation : xsd:decimal [0..1]
}
class "epo:ReviewTerm" {
  epo:definesReviewer : epo:Reviewer [0..*]
  epo:definesReviewProcedureInformationProvider : epo:ReviewProcedureInformationProvider [0..1]
  epo:hasReviewDeadline : xsd:dateTime [0..1]
  epo:hasReviewDeadlineInformation : rdf:PlainLiteral [0..*]
  epo:hasReviewProcedure : rdf:PlainLiteral [0..*]
}
class "epo:Prize" {
  epo:hasPrizeRank : xsd:integer [0..1]
  epo:hasPrizeValue : epo:MonetaryValue [0..1]
}
class "epo:Procedure" {
  epo:hasAcceleratedProcedureJustification : rdf:PlainLiteral [0..*]
  epo:hasMainFeature : rdf:PlainLiteral [0..*]
  epo:hasProcedureType : at-voc:procurement-procedure-type [1]
  epo:hasProcurementScopeDividedIntoLot : epo:Lot [1..*]
  epo:involvesBuyer : epo:Buyer [0..*]
  epo:isAccelerated : xsd:boolean [0..1]
  epo:isDesignContest : xsd:boolean [0..1]
  epo:isExecutedByProcurementServiceProvider : epo:ProcurementServiceProvider [0..1]
  epo:isJointProcurement : xsd:boolean [0..1]
  epo:isResponsibilityOfBuyer : epo:Buyer [0..*]
  epo:isSubjectToProcedureSpecificTerm : epo:ProcedureSpecificTerm [1..*]
  epo:specifiesProcurementCriteriaSummary : epo:ProcurementCriteriaSummary [0..*]
}
class "epo:ParticipationRequestTerm" {
  epo:definesParticipationRequestProcessor : epo:ParticipationRequestProcessor [0..1]
  epo:definesParticipationRequestReceiver : epo:ParticipationRequestReceiver [0..1]
}
class "epo:ProcedureTerm" {
  epo:definesBudgetProvider : epo:BudgetProvider [0..1]
  epo:definesInformationProvider : epo:AuxiliaryParty [0..*]
  epo:definesLotGroup : epo:LotGroup [0..*]
  epo:definesMediator : epo:Mediator [0..1]
  epo:hasCrossBorderLaw : rdf:PlainLiteral [0..*]
  epo:hasGroupLotEvaluationMethod : rdf:PlainLiteral [0..*]
  epo:hasLotAwardCombination : rdf:PlainLiteral [0..1]
  epo:hasMaximumLotSubmissionAllowed : xsd:integer [0..1]
  epo:hasMaximumNumberOfLotsToBeAwarded : xsd:integer [0..1]
  epo:hasNationalProcedureRules : xsd:anyURI [0..*]
  epo:isAwardedByCPB : xsd:boolean [0..1]
  epo:isOneLotOnlyAllowed : xsd:boolean [0..1]
  epo:isSubmissionForAllLotsRequired : xsd:boolean [0..1]
}
class "epo:ProcurementCriterion" {
  epo:hasConstraint : cccev:Constraint [0..*]
  epo:hasFormula : rdf:PlainLiteral [0..1]
  epo:hasPerformingStaffQualificationInformation : at-voc:requirement-stage [0..*]
  epo:hasWeightValueType : at-voc:number-weight [0..1]
}
class "epo:TenderGroup" {
  adms:identifier : adms:Identifier [0..1]
  dct:description : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  epo:comprisesTender : epo:Tender [1..*]
  epo:hasTotalValue : epo:MonetaryValue [0..1]
  epo:isSubmittedForLotGroup : epo:LotGroup [1]
}
class "epo:Duration" {

}
class "epo:ProcurementDocument" {

}
class "epo:ProcurementServiceProvider" {
  epo:actsOnBehalfOf : epo:Buyer [1..*]
}
class "epo:ProcedureSpecificTerm" {

}
class "epo:NonDisclosureAgreementTerm" {
  dct:description : rdf:PlainLiteral [0..1]
  epo:isNonDisclosureAgreementRequired : xsd:boolean [0..1]
}
class "epo:PurchaseContract" {
  epo:followsRulesSetBy : epo:FrameworkAgreement [0..1]
  epo:resultsFromMiniCompetitionAwardOutcome : epo:MiniCompetitionAwardOutcome [0..1]
}
class "epo:Purpose" {
  epo:hasAdditionalClassification : at-voc:cpv [0..*]
  epo:hasMainClassification : at-voc:cpv [1..*]
  epo:hasTotalQuantity : epo:Quantity [0..1]
}
class "epo:Reviewer" {
  epo:hasReviewBodyType : at-voc:review-body-type [0..*]
}
class "epo:Offer" {

}
class "epo:SecurityClearanceTerm" {
  dct:description : rdf:PlainLiteral [0..*]
  epo:hasDeadline : xsd:dateTime [0..1]
  epo:isSecurityClearanceRequired : xsd:boolean [0..1]
}
class "epo:SelectionCriterion" {
  epo:hasSelectionCriteriaUsage : at-voc:usage [0..1]
  epo:hasSelectionCriterionType : at-voc:selection-criterion [0..1]
  epo:isUsedForCandidateRestriction : xsd:boolean [0..1]
}
class "epo:SocialProcurement" {
  epo:fulfillsRequirement : at-voc:social-objective [0..*]
}
class "epo:StatisticalInformation" {

}
class "epo:StrategicProcurement" {
  epo:hasNonAccessibilityCriterionJustification : rdf:PlainLiteral [0..*]
  epo:hasStrategicProcurementDescription : rdf:PlainLiteral [0..*]
  epo:includesAccessibilityCriterion : at-voc:accessibility [0..*]
}
class "epo:Subcontractor" {

}
class "epo:SubcontractTerm" {
  dct:description : rdf:PlainLiteral [0..*]
  epo:hasMaximumShare : xsd:decimal [0..1]
  epo:hasMinimumShare : xsd:decimal [0..1]
  epo:hasMinimumSubcontractorsProposedObligation : xsd:decimal [0..1]
  epo:hasSubcontractingInvolved : xsd:boolean [0..1]
  epo:hasSubcontractingObligation : at-voc:subcontracting-obligation [0..*]
  epo:hasSubcontractorsProposedAboveObligation : xsd:decimal [0..1]
}
class "epo:SubmissionTerm" {
  epo:definesTenderProcessor : epo:TenderProcessor [0..1]
  epo:definesTenderReceiver : epo:TenderReceiver [0..1]
  epo:hasEAuctionURL : xsd:anyURI [0..1]
  epo:hasECataloguePermission : at-voc:permission [0..1]
  epo:hasESubmissionPermission : at-voc:permission [0..1]
  epo:hasGuaranteeDescription : rdf:PlainLiteral [0..*]
  epo:hasLanguage : at-voc:language [0..*]
  epo:hasLateSubmissionInformationDescription : rdf:PlainLiteral [0..*]
  epo:hasLateSubmissionPermission : at-voc:missing-info-submission [0..1]
  epo:hasNonElectronicSubmissionDescription : rdf:PlainLiteral [0..*]
  epo:hasNonElectronicSubmissionJustification : at-voc:communication-justification [0..*]
  epo:hasReceiptDeadline : xsd:dateTime [0..1]
  epo:hasReceiptExpressionDeadline : xsd:dateTime [0..1]
  epo:hasReceiptParticipationRequestDeadline : xsd:dateTime [0..1]
  epo:hasReceiptPreliminaryMarketConsultationDeadline : xsd:dateTime [0..1]
  epo:hasReceiptTenderDeadline : xsd:dateTime [0..1]
  epo:hasSubmissionURL : xsd:anyURI [0..*]
  epo:hasTenderSubcontractingInformation : at-voc:subcontracting-indication [0..*]
  epo:hasTenderValidityDuration : epo:Duration [0..1]
  epo:hasTenderValidityPeriod : epo:Period [0..1]
  epo:hasVariantPermission : at-voc:permission [0..1]
  epo:isAdvancedElectronicSignatureRequired : xsd:boolean [0..1]
  epo:isGuaranteeRequired : xsd:boolean [0..1]
  epo:isMultipleTenderSubmissionAllowed : xsd:boolean [0..1]
}
class "epo:System" {
  dct:description : rdf:PlainLiteral [0..*]
  epo:isOwnedByAgent : foaf:Agent [0..1]
}
class "epo:Technique" {
  dct:description : rdf:PlainLiteral [0..*]
  epo:hasUsage : at-voc:usage [0..1]
  epo:hasValidityPeriod : epo:Period [0..1]
}
class "epo:Tenderer" {
  epo:substantiatesExclusionGround : epo:ExclusionGround [0..1]
}
class "epo:Tender" {
  epo:foreseesConcession : epo:ConcessionEstimate [0..1]
  epo:foreseesSubcontracting : epo:SubcontractingEstimate [0..*]
  epo:hasElectronicSubmission : xsd:boolean [0..1]
  epo:hasFinancialOfferValue : epo:MonetaryValue [0..1]
  epo:hasItemCountryOfOrigin : at-voc:country [0..*]
  epo:hasSubcontracting : at-voc:applicability [0..1]
  epo:isSubjectToGrouping : epo:LotGroup [0..1]
  epo:isSubmitedBy : epo:Tenderer [0..1]
  epo:isSubmittedForLot : epo:Lot [1]
  epo:isVariant : xsd:boolean [0..1]
  epo:specifiesSubcontractors : epo:Subcontractor [0..*]
}
class "epo:MonetaryValue" {
  epo:hasAmountValue : xsd:decimal [1..1]
  epo:hasCurrency : at-voc:currency [0..1]
  epo:hasCurrencyCodeListAgencyID : rdf:PlainLiteral [0..*]
  epo:hasCurrencyCodeListAgencyName : rdf:PlainLiteral [0..*]
  epo:hasCurrencyCodeListID : rdf:PlainLiteral [0..*]
}
class "epo:Winner" {
  epo:needsToBeATenderer : epo:Tenderer [0..1]
}
class "epo:JuryMember" {
  epo:playedBy : person:Person [0..1]
}
class "epo:ProcurementProcedureInformationProvider" {

}
class "epo:Quantity" {
  epo:hasQuantityValue : xsd:decimal [1..1]
  epo:hasUnitCode : at-voc:measurement-unit [1]
  epo:hasUnitDescription : rdf:PlainLiteral [0..*]
}
class "epo:OriginatorRequest" {

}
class "epo:PaymentExecutor" {

}
class "epo:BudgetProvider" {

}
class "epo:ParticipationRequestProcessor" {

}
class "epo:ParticipationRequestReceiver" {

}
class "epo:TenderReceiver" {

}
class "epo:TenderProcessor" {

}
class "epo:OfflineAccessProvider" {

}
class "epo:ReviewProcedureInformationProvider" {

}
class "epo:Term" {

}
class "epo:TenderAwardOutcome" {
  epo:concernsTender : epo:Tender [1]
  epo:hasAwardRank : xsd:integer [0..1]
  epo:indicatesAwardToWinner : epo:Winner [0..1]
}
class "epo:LotAwardOutcome" {
  epo:concernsLot : epo:Lot [1]
  epo:hasApproximateFrameworkAgreementValue : epo:MonetaryValue [0..1]
  epo:hasFrameworkAgreementMaximumValue : epo:MonetaryValue [0..1]
  epo:hasNonAwardedContractNumber : rdf:PlainLiteral [0..1]
  epo:hasNonAwardedContractTitle : rdf:PlainLiteral [0..1]
}
class "epo:ReviewRequestSummary" {
  epo:concernsReviewSummaryForLot : epo:Lot [1]
  epo:hasReviewIrregularitySummary : epo:ReviewIrregularitySummary [0..*]
  epo:hasTotalNumberOfComplainants : xsd:integer [0..1]
}
class "epo:LotGroupAwardInformation" {
  epo:describesLotGroup : epo:LotGroup [1]
  epo:hasGroupFrameworkAgreementMaximumValue : epo:MonetaryValue [0..1]
}
class "epo:NoticeAwardInformation" {
  epo:describesDirectAwardPrenotificationNotice : epo-not:DirectAwardPrenotificationNotice [0..1]
  epo:describesResultNotice : epo-not:ResultNotice [0..1]
  epo:hasApproximateFrameworkAgreementValue : epo:MonetaryValue [0..1]
  epo:hasMaximumFrameworkAgreementAwardedValue : epo:MonetaryValue [0..1]
  epo:hasProcurementHighestReceivedTenderValue : epo:MonetaryValue [0..1]
  epo:hasProcurementLowestReceivedTenderValue : epo:MonetaryValue [0..1]
  epo:hasTotalAwardedValue : epo:MonetaryValue [0..1]
}
class "epo:ReviewDecision" {
  epo:hasConfirmedIrregularityType : at-voc:irregularity-type [0..*]
  epo:hasDecisionDate : xsd:date [0..1]
  epo:hasRemedyValue : epo:MonetaryValue [0..1]
  epo:hasReviewDecisionType : at-voc:review-decision-type [0..*]
  epo:providesRulingOnRemedy : at-voc:remedy-type [0..*]
  epo:resolvesReviewRequest : epo:ReviewRequest [1]
}
class "epo:AgentInRole" {
  dct:description : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  epo:contextualisedBy : epo:ProcurementObject [0..*]
  epo:exposesChannel : cv:Channel [0..*]
  epo:hasContactPointInRole : cpov:ContactPoint [0..*]
  epo:playedBy : foaf:Agent [1]
}
class "epo:TaxInformationProvider" {

}
class "epo:EmploymentInformationProvider" {

}
class "epo:EnvironmentalProtectionInformationProvider" {

}
class "epo:Awarder" {

}
class "epo:ReviewRequest" {
  epo:hasAllegedIrregularityType : at-voc:irregularity-type [1..*]
  epo:hasNumberOfReviewRequests : xsd:integer [1..1]
  epo:hasRequestDate : xsd:date [0..1]
  epo:hasReviewRequestFee : epo:MonetaryValue [0..1]
  epo:hasWithdrawalDate : xsd:date [0..1]
  epo:hasWithdrawalReason : rdf:PlainLiteral [0..1]
  epo:isWithdrawn : xsd:boolean [0..1]
  epo:requestsRemedyType : at-voc:remedy-type [0..*]
}
class "epo:SubmissionStatisticalInformation" {
  epo:hasAbnormallyLowTenders : xsd:integer [0..1]
  epo:hasEEAReceivedTenders : xsd:integer [0..1]
  epo:hasElectronicTenders : xsd:integer [0..1]
  epo:hasEstimatedTotalSubcontracts : xsd:integer [0..1]
  epo:hasEUReceivedTenders : xsd:integer [0..1]
  epo:hasHighestReceivedTenderValue : epo:MonetaryValue [0..1]
  epo:hasInadmissibleTenders : xsd:integer [0..1]
  epo:hasLowestReceivedTenderValue : epo:MonetaryValue [0..1]
  epo:hasMediumTenderPerLots : xsd:integer [0..1]
  epo:hasNonEEAReceivedTenders : xsd:integer [0..1]
  epo:hasNonEUReceivedTenders : xsd:integer [0..1]
  epo:hasNumberOfTenderersInvited : xsd:integer [0..1]
  epo:hasOtherCountriesReceivedTenders : xsd:integer [0..1]
  epo:hasReceivedMicroTenders : xsd:integer [0..1]
  epo:hasReceivedParticipationRequests : xsd:integer [0..1]
  epo:hasReceivedSmallTenders : xsd:integer [0..1]
  epo:hasReceivedSubmissionType : at-voc:received-submission-type [0..1]
  epo:hasReceivedTenders : xsd:integer [0..1]
  epo:hasSMEReceivedTenders : xsd:integer [0..1]
  epo:hasUnverifiedTenders : xsd:integer [0..1]
  epo:summarisesInformationForAwardOutcome : epo:AwardOutcome [1]
}
class "epo:ProcurementObject" {
  epo:foreseesConcession : epo:ConcessionEstimate [0..1]
  epo:foreseesContractSpecificTerm : epo:ContractSpecificTerm [0..*]
  epo:fulfillsStrategicProcurement : epo:StrategicProcurement [0..*]
  epo:hasAdditionalInformation : rdf:PlainLiteral [0..*]
  epo:hasLaunchFrameworkAgreementMaximumValue : epo:MonetaryValue [0..1]
  epo:hasLegalBasis : at-voc:legal-basis [0..*]
  epo:hasLegalBasisDescription : rdf:PlainLiteral [0..*]
  epo:hasPurpose : epo:Purpose [0..1]
  epo:hasRecurrenceDescription : rdf:PlainLiteral [0..1]
  epo:isCoveredByGPA : xsd:boolean [0..1]
  epo:isFundedBy : epo:Fund [0..*]
  epo:isRecurrent : xsd:boolean [0..1]
  epo:isSMESuitable : xsd:boolean [0..1]
  epo:isSubjectToTerm : epo:Term [0..*]
  epo:isUsingEUFunds : xsd:boolean [0..1]
  epo:usesTechnique : epo:Technique [0..*]
}
class "epo:ContextDescription" {

}
class "epo:ContextualProjection" {

}
class "epo:ChangeInformation" {
  epo:concernsNotice : epo:Notice [1]
  epo:hasAdditionalInformation : rdf:PlainLiteral [0..1]
  epo:hasChangeDescription : rdf:PlainLiteral [0..*]
  epo:hasChangeJustification : at-voc:change-corrig-justification [1]
  epo:hasChangeReasonDescription : rdf:PlainLiteral [0..*]
  epo:hasProcurementDocumentChangeDate : xsd:dateTime [0..1]
  epo:isProcurementDocumentChanged : xsd:boolean [0..1]
  epo:refersToPreviousNotice : epo:Notice [1]
  epo:relatesToEFormSectionIdentifier : adms:Identifier [1..*]
}
class "epo:ReviewObject" {
  epo:hasElementReference : xsd:anyURI [0..*]
  epo:hasReviewURL : xsd:anyURI [0..1]
  epo:refersToPreviousReview : epo:ReviewObject [0..1]
}
class "epo:ReviewIrregularitySummary" {
  epo:hasIrregularityType : at-voc:irregularity-type [1]
  epo:hasReviewIrregularityCount : xsd:integer [1..1]
}
class "epo:ContractSpecificTerm" {

}
class "epo:ConcessionContract" {

}
class "epo:ProcessPlanningTerm" {
  epo:hasAwardDateScheduled : xsd:date [0..1]
  epo:hasEstimatedContractNoticePublicationDate : xsd:date [0..1]
  epo:hasEstimatedTenderInvitationDate : xsd:date [0..1]
}
class "epo:ProcurementProcessInformation" {
  epo:concernsLot : epo:Lot [0..1]
  epo:concernsProcedure : epo:Procedure [0..1]
  epo:isCompetitionTerminated : xsd:boolean [0..1]
  epo:isDPSTerminated : xsd:boolean [0..1]
  epo:isToBeRelaunched : xsd:boolean [0..1]
}
class "epo:CertificationLabel" {
  epo:hasLabelType : at-voc-new:certification-label-type [0..1]
  epo:hasReferenceURI : xsd:anyURI [0..1]
}
class "epo:Certifier" {

}
class "epo:Certificate" {
  epo:attestedByLabel : epo:CertificationLabel [1]
  epo:hasCertificationNumber : rdf:PlainLiteral [1..1]
  epo:hasURL : xsd:anyURI [0..1]
  epo:issuedByCertifier : epo:Certifier [0..1]
}
class "epo:AcquiringParty" {

}
class "epo:AuxiliaryParty" {

}
class "epo:OtherEntity" {

}
class "epo:SpecificDuration" {
  time:numericDuration : xsd:decimal [1..1]
  time:unitType : time:TemporalUnit [1]
}
class "epo:IndefiniteDuration" {

}
class "epo:ProcurementElement" {
  adms:identifier : adms:Identifier [1]
  dct:description : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  epo:hasEstimatedValue : epo:MonetaryValue [0..1]
  epo:hasInternalIdentifier : adms:Identifier [0..*]
  epo:usesChannel : cv:Channel [0..*]
}
class "epo:LeadBuyer" {

}
class "epo:DirectContract" {
  epo:resultsFromLotAwardOutcome : epo:LotAwardOutcome [0..*]
}
class "epo:AwardCriteriaSummary" {

}
class "epo:OfferIssuer" {
  epo:distributesOffer : epo:Offer [0..*]
}
class "epo:ParticipationCondition" {
  epo:hasReservedProcurement : at-voc:reserved-procurement [0..*]
}
class "epo:ProcurementCriteriaSummary" {
  epo:indicatesPerformingStaffInformationRequirement : xsd:boolean [0..1]
}
class "epo:ParticipationConditionsSummary" {
  epo:describesObjectiveParticipationRules : rdf:PlainLiteral [0..1]
  epo:describesVerificationMethod : rdf:PlainLiteral [0..1]
  epo:hasReservedProcurement : at-voc:reserved-procurement [0..*]
}
class "epo:ExclusionGroundsSummary" {

}
class "epo:SelectionCriteriaSummary" {
  epo:describesMinimumLevelOfStandards : rdf:PlainLiteral [0..1]
  epo:hasSelectionCriteriaStatedInProcurementDocuments : xsd:boolean [0..1]
}
class "epo:Candidate" {

}
class "epo:Project" {
  adms:identifier : adms:Identifier [0..1]
}
class "epo:SelectedCandidateList" {
  epo:containsCandidate : epo:Candidate [0..*]
  epo:hasStartDate : epo:Period [0..1]
}
class "epo:MiniCompetitionAwardOutcome" {
  epo:resultsFromUsingCandidateList : epo:SelectedCandidateList [0..1]
}
class "epo:ElectronicSignature" {
  dct:description : rdf:PlainLiteral [1..1]
}
class "epo:AdHocChannel" {

}
class "epo:ProfessionalSuitabilitySummary" {
  epo:describesProfession : rdf:PlainLiteral [0..1]
  epo:describesProfessionRelevantLaw : rdf:PlainLiteral [0..1]
  epo:hasServiceReservedToParticularProfession : xsd:boolean [0..1]
}
class "epo:EconomicStandingSummary" {

}
class "epo:TechnicalAbilitySummary" {

}
class "epo:QualificationCriteriaSummary" {
  epo:hasConditionVerificationMethod : rdf:PlainLiteral [0..*]
  epo:hasQualificationCondition : rdf:PlainLiteral [0..*]
}
class "epo:QualificationCriterion" {

}
"cccev:Criterion" <|-- "epo:ProcurementCriterion"
"cccev:Evidence" <|-- "epo:Certificate"
"cccev:InformationConcept" <|-- "epo:CertificationLabel"
"cccev:Requirement" <|-- "epo:ProcurementCriteriaSummary"
"cv:Channel" <|-- "epo:AdHocChannel"
"epo:AcquiringParty" <|-- "epo:Awarder"
"epo:AcquiringParty" <|-- "epo:BudgetProvider"
"epo:AcquiringParty" <|-- "epo:Buyer"
"epo:AcquiringParty" <|-- "epo:CatalogueReceiver"
"epo:AcquiringParty" <|-- "epo:JuryMember"
"epo:AcquiringParty" <|-- "epo:Mediator"
"epo:AcquiringParty" <|-- "epo:OfflineAccessProvider"
"epo:AcquiringParty" <|-- "epo:ParticipationRequestProcessor"
"epo:AcquiringParty" <|-- "epo:ParticipationRequestReceiver"
"epo:AcquiringParty" <|-- "epo:PaymentExecutor"
"epo:AcquiringParty" <|-- "epo:ProcurementProcedureInformationProvider"
"epo:AcquiringParty" <|-- "epo:ProcurementServiceProvider"
"epo:AcquiringParty" <|-- "epo:ReviewProcedureInformationProvider"
"epo:AcquiringParty" <|-- "epo:Reviewer"
"epo:AcquiringParty" <|-- "epo:TenderProcessor"
"epo:AcquiringParty" <|-- "epo:TenderReceiver"
"epo:AgentInRole" <|-- "epo:AcquiringParty"
"epo:AgentInRole" <|-- "epo:AuxiliaryParty"
"epo:AgentInRole" <|-- "epo:OfferingParty"
"epo:AuxiliaryParty" <|-- "epo:Certifier"
"epo:AuxiliaryParty" <|-- "epo:EmploymentInformationProvider"
"epo:AuxiliaryParty" <|-- "epo:EnvironmentalProtectionInformationProvider"
"epo:AuxiliaryParty" <|-- "epo:TaxInformationProvider"
"epo:AwardOutcome" <|-- "epo:LotAwardOutcome"
"epo:AwardOutcome" <|-- "epo:MiniCompetitionAwardOutcome"
"epo:Buyer" <|-- "epo:CentralPurchasingBody"
"epo:Buyer" <|-- "epo:LeadBuyer"
"epo:CentralPurchasingBody" <|-- "epo:AcquiringCentralPurchasingBody"
"epo:CentralPurchasingBody" <|-- "epo:AwardingCentralPurchasingBody"
"epo:ContextDescription" <|-- "epo:ChangeInformation"
"epo:ContextDescription" <|-- "epo:ContractLotCompletionInformation"
"epo:ContextDescription" <|-- "epo:Estimate"
"epo:ContextDescription" <|-- "epo:LotGroupAwardInformation"
"epo:ContextDescription" <|-- "epo:NonPublishedInformation"
"epo:ContextDescription" <|-- "epo:NoticeAwardInformation"
"epo:ContextDescription" <|-- "epo:ProcurementProcessInformation"
"epo:ContextDescription" <|-- "epo:StatisticalInformation"
"epo:ContextualProjection" <|-- "epo:AwardOutcome"
"epo:ContextualProjection" <|-- "epo:TenderAwardOutcome"
"epo:Contract" <|-- "epo:ConcessionContract"
"epo:Contract" <|-- "epo:DirectContract"
"epo:Contract" <|-- "epo:FrameworkAgreement"
"epo:Contract" <|-- "epo:PurchaseContract"
"epo:ContractSpecificTerm" <|-- "epo:ContractTerm"
"epo:ContractSpecificTerm" <|-- "epo:FrameworkAgreementTerm"
"epo:ContractSpecificTerm" <|-- "epo:SubcontractTerm"
"epo:Document" <|-- "epo:AwardDecision"
"epo:Document" <|-- "epo:Contract"
"epo:Document" <|-- "epo:ExpressionOfInterest"
"epo:Document" <|-- "epo:Notice"
"epo:Document" <|-- "epo:Offer"
"epo:Document" <|-- "epo:OriginatorRequest"
"epo:Document" <|-- "epo:ProcurementDocument"
"epo:Document" <|-- "epo:RequestForClarification"
"epo:Document" <|-- "epo:RequestForParticipation"
"epo:Document" <|-- "epo:ReviewObject"
"epo:Document" <|-- "epo:Tender"
"epo:Duration" <|-- "epo:IndefiniteDuration"
"epo:Duration" <|-- "epo:SpecificDuration"
"epo:Estimate" <|-- "epo:ConcessionEstimate"
"epo:Estimate" <|-- "epo:SubcontractingEstimate"
"epo:EvaluationTerm" <|-- "epo:AwardEvaluationTerm"
"epo:EvaluationTerm" <|-- "epo:SelectionEvaluationTerm"
"epo:LotSpecificTerm" <|-- "epo:AccessTerm"
"epo:LotSpecificTerm" <|-- "epo:DesignContestRegimeTerm"
"epo:LotSpecificTerm" <|-- "epo:EvaluationTerm"
"epo:LotSpecificTerm" <|-- "epo:FrameworkAgreementTerm"
"epo:LotSpecificTerm" <|-- "epo:MultipleStageProcedureTerm"
"epo:LotSpecificTerm" <|-- "epo:NonDisclosureAgreementTerm"
"epo:LotSpecificTerm" <|-- "epo:OpeningTerm"
"epo:LotSpecificTerm" <|-- "epo:ParticipationRequestTerm"
"epo:LotSpecificTerm" <|-- "epo:ReviewTerm"
"epo:LotSpecificTerm" <|-- "epo:SecurityClearanceTerm"
"epo:LotSpecificTerm" <|-- "epo:SubmissionTerm"
"epo:OfferingParty" <|-- "epo:Candidate"
"epo:OfferingParty" <|-- "epo:CatalogueProvider"
"epo:OfferingParty" <|-- "epo:Contractor"
"epo:OfferingParty" <|-- "epo:OfferIssuer"
"epo:OfferingParty" <|-- "epo:OtherEntity"
"epo:OfferingParty" <|-- "epo:ReviewRequester"
"epo:OfferingParty" <|-- "epo:Subcontractor"
"epo:OfferingParty" <|-- "epo:Tenderer"
"epo:OfferingParty" <|-- "epo:Winner"
"epo:ProcedureSpecificTerm" <|-- "epo:AccessTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:DesignContestRegimeTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:DirectAwardTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:FrameworkAgreementTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:OpeningTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:ProcedureTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:ReviewTerm"
"epo:ProcedureSpecificTerm" <|-- "epo:SubmissionTerm"
"epo:ProcurementCriteriaSummary" <|-- "epo:AwardCriteriaSummary"
"epo:ProcurementCriteriaSummary" <|-- "epo:ParticipationConditionsSummary"
"epo:ProcurementCriteriaSummary" <|-- "epo:QualificationCriteriaSummary"
"epo:ProcurementCriterion" <|-- "epo:AwardCriterion"
"epo:ProcurementCriterion" <|-- "epo:ParticipationCondition"
"epo:ProcurementCriterion" <|-- "epo:QualificationCriterion"
"epo:ProcurementElement" <|-- "epo:PlannedProcurementPart"
"epo:ProcurementElement" <|-- "epo:ProcurementObject"
"epo:ProcurementObject" <|-- "epo:Lot"
"epo:ProcurementObject" <|-- "epo:Procedure"
"epo:QualificationCriteriaSummary" <|-- "epo:ExclusionGroundsSummary"
"epo:QualificationCriteriaSummary" <|-- "epo:SelectionCriteriaSummary"
"epo:QualificationCriterion" <|-- "epo:ExclusionGround"
"epo:QualificationCriterion" <|-- "epo:SelectionCriterion"
"epo:ReviewObject" <|-- "epo:ReviewDecision"
"epo:ReviewObject" <|-- "epo:ReviewRequest"
"epo:SelectionCriteriaSummary" <|-- "epo:EconomicStandingSummary"
"epo:SelectionCriteriaSummary" <|-- "epo:ProfessionalSuitabilitySummary"
"epo:SelectionCriteriaSummary" <|-- "epo:TechnicalAbilitySummary"
"epo:StatisticalInformation" <|-- "epo:ReviewIrregularitySummary"
"epo:StatisticalInformation" <|-- "epo:ReviewRequestSummary"
"epo:StatisticalInformation" <|-- "epo:SubmissionStatisticalInformation"
"epo:StrategicProcurement" <|-- "epo:GreenProcurement"
"epo:StrategicProcurement" <|-- "epo:InnovativeProcurement"
"epo:StrategicProcurement" <|-- "epo:SocialProcurement"
"epo:Technique" <|-- "epo:DynamicPurchaseSystemTechnique"
"epo:Technique" <|-- "epo:EAuctionTechnique"
"epo:Technique" <|-- "epo:FrameworkAgreementTechnique"
"epo:Term" <|-- "epo:ContractSpecificTerm"
"epo:Term" <|-- "epo:LotSpecificTerm"
"epo:Term" <|-- "epo:ProcedureSpecificTerm"
"epo:Term" <|-- "epo:ProcessPlanningTerm"
"foaf:Agent" <|-- "epo:System"
"org:Organization" <|-- "epo:Business"
"org:Organization" <|-- "epo:OrganisationGroup"
"time:Duration" <|-- "epo:Duration"
@enduml
