
@startuml
class "epo-cat:PostAwardDocument" {
  epo-cat:hasDocumentType : at-voc-new:document-type [0..1]
  epo:hasDocumentStatus : at-voc-new:document-status [0..1]
}
class "epo-cat:Catalogue" {
  epo-cat:comprisesCatalogueLine : epo-cat:CatalogueLine [1..*]
  epo-cat:hasActivityCode : at-voc-new:activity-code [0..1]
  epo-cat:hasSpecificPaymentArrangement : rdf:PlainLiteral [0..1]
  epo-cat:isSubordinatedToContract : epo:Contract [0..1]
  epo:specifiesBuyer : epo:Buyer [0..*]
  epo:specifiesCatalogueProvider : epo:CatalogueProvider [0..1]
  epo:specifiesCatalogueReceiver : epo:CatalogueReceiver [0..1]
  epo:specifiesSeller : epo-ord:Seller [0..*]
}
class "epo-cat:CatalogueLine" {
  epo-cat:hasActivityCode : at-voc-new:activity-code [0..1]
  epo-cat:hasCatalogueLineValidity : epo:Period [0..1]
  epo-cat:hasChargeInformation : epo-cat:ChargeInformation [0..*]
  epo-cat:hasMaximumOrderQuantity : epo:Quantity [0..1]
  epo-cat:hasMinimumQuantityGuaranteedForDelivery : epo:Quantity [0..1]
  epo-cat:hasOrderableQuantityIncrement : xsd:integer [0..1]
  epo-cat:hasOrderableUnit : at-voc-new:orderable-unit [0..1]
  epo-cat:hasOrderableUnitFactorRate : xsd:decimal [0..1]
  epo-cat:hasPrice : epo-cat:Price [1..*]
  epo-cat:hasStandardisedUnitPrice : epo-cat:Price [0..*]
  epo-cat:hasTransactionConditions : rdf:PlainLiteral [0..1]
  epo-cat:hasTransactionConditionsCode : at-voc-new:transaction-conditions [0..1]
  epo-cat:hasWarrantyInformation : rdf:PlainLiteral [0..1]
  epo-cat:isContractedItem : xsd:boolean [0..1]
  epo-cat:isOrderable : xsd:boolean [0..1]
}
class "epo-cat:ItemRequirement" {

}
class "epo-cat:Item" {
  dct:description : rdf:PlainLiteral [0..1]
  dct:hasPart : epo-cat:Item [0..*]
  dct:isReplacedBy : epo-cat:Item [0..*]
  dct:requires : epo-cat:Item [0..*]
  dct:title : rdf:PlainLiteral [1..1]
  epo-cat:hasAccessoryItem : epo-cat:Item [0..*]
  epo-cat:hasBrand : epo-cat:Brand [0..1]
  epo-cat:hasComplementaryItem : epo-cat:Item [0..*]
  epo-cat:hasCountryOfOrigin : at-voc:country [0..1]
  epo-cat:hasDeliveryClassification : at-voc-new:delivery-item-type [0..1]
  epo-cat:hasDimensionDescription : rdf:PlainLiteral [0..*]
  epo-cat:hasExternalSpecification : epo:Document 
  epo-cat:hasHazardousClass : rdf:PlainLiteral [0..*]
  epo-cat:hasHazardousItemUNDGCode : at-voc-new:dangerous-goods-list [0..*]
  epo-cat:hasItemClassification : at-voc-new:item-classification [0..*]
  epo-cat:hasKeyword : rdf:PlainLiteral [0..*]
  epo-cat:hasManufacturer : epo-cat:Manufacturer [0..1]
  epo-cat:hasModel : epo-cat:ItemModel [0..1]
  epo-cat:hasNetQuantity : epo:Quantity [0..1]
  epo-cat:hasQualifiedItemRelation : epo-cat:ItemRelation [0..*]
  epo-cat:hasSpecification : epo-cat:ProductSpecification [0..*]
  epo-cat:isInStock : xsd:boolean [0..1]
  epo-ord:hasTaxInformation : epo-ord:TaxInformation [0..*]
  epo:hasBuyerItemID : adms:Identifier [0..1]
  epo:hasCertification : epo:Certificate [0..*]
  epo:hasItemStandardID : adms:Identifier [0..*]
  epo:hasManufacturerItemID : adms:Identifier [0..1]
  epo:hasSellerItemID : adms:Identifier [0..1]
  epo:hasSerialID : adms:Identifier [0..1]
}
class "epo-cat:Price" {
  epo-cat:hasBaseQuantity : epo:Quantity [0..1]
  epo-cat:hasDeliveryLocation : dct:Location [0..1]
  epo-cat:hasExpectedDeliveryTime : epo:Duration [0..1]
  epo-cat:hasNetMonetaryValue : epo:MonetaryValue [1]
  epo-cat:hasOrderabableUnitFactorRate : epo:Quantity [0..1]
  epo-cat:hasPriceType : at-voc-new:price-type [0..1]
  epo-cat:hasPriceValidity : epo:Period [1]
  epo-cat:hasQuantityThreshold : epo:Quantity [0..1]
  epo-ord:hasPriceDiscountInformation : epo-ord:AllowanceInformation [0..1]
  epo:hasPriceSurchargeInformation : epo-cat:ChargeInformation [0..1]
}
class "epo-cat:ProductSpecification" {

}
class "epo-cat:ItemComposition" {

}
class "epo-cat:ItemProperty" {
  epo-cat:describesItem : epo-cat:Item [1]
  epo-cat:hasAttributeType : rdf:PlainLiteral [1..1]
  epo-cat:hasClassificationScheme : rdf:PlainLiteral [1..1]
  epo-cat:hasLiteralValue : rdf:PlainLiteral [0..1]
  epo-cat:hasQualifiedValue : epo:Quantity [0..1]
}
class "epo-cat:Manufacturer" {
  epo:hasManufacturerID : adms:Identifier [0..1]
}
class "epo-cat:Batch" {
  epo-cat:hasBestBeforeDate : xsd:date [0..1]
  epo-cat:hasExpiryDate : xsd:date [0..1]
  epo-cat:hasManufactureDate : xsd:dateTime [0..1]
  epo-cat:isProductionOf : epo-cat:Item [1]
  epo:hasBatchID : adms:Identifier [0..1]
}
class "epo-cat:Brand" {
  dct:title : rdf:PlainLiteral [1..1]
}
class "epo-cat:ItemModel" {
  dct:title : rdf:PlainLiteral [1..1]
}
class "epo-cat:ItemReplacement" {

}
class "epo-cat:ItemRelation" {
  epo-cat:hasFactor : xsd:decimal [0..1]
  epo-cat:isRelatedToItem : epo-cat:Item [1]
}
class "epo-cat:ItemAccessoryRelation" {

}
class "epo-cat:ItemComplementaryRelation" {

}
class "epo-cat:ChargeInformation" {
  epo-ord:isSpecificToOrderLine : epo-ord:OrderLine [0..*]
}
class "epo-cat:Line" {
  adms:identifier : adms:Identifier [0..1]
  dct:description : rdf:PlainLiteral [0..1]
  epo-cat:specifiesItem : epo-cat:Item [1]
}
class "epo-cat:InformationHub" {
  epo-cat:isSpecificToLine : epo-cat:Line [0..*]
}
"epo-cat:ItemRelation" <|-- "epo-cat:ItemAccessoryRelation"
"epo-cat:ItemRelation" <|-- "epo-cat:ItemComplementaryRelation"
"epo-cat:ItemRelation" <|-- "epo-cat:ItemComposition"
"epo-cat:ItemRelation" <|-- "epo-cat:ItemReplacement"
"epo-cat:ItemRelation" <|-- "epo-cat:ItemRequirement"
"epo-cat:Line" <|-- "epo-cat:CatalogueLine"
"epo-cat:PostAwardDocument" <|-- "epo-cat:Catalogue"
"epo-cat:PostAwardDocument" <|-- "epo-cat:ProductSpecification"
"epo-ord:AllowanceChargeInformation" <|-- "epo-cat:ChargeInformation"
"epo:ContextDescription" <|-- "epo-cat:InformationHub"
"epo:Document" <|-- "epo-cat:PostAwardDocument"
"epo:OfferingParty" <|-- "epo-cat:Manufacturer"
@enduml
