# How many tenders foresee subcontracting for a given date?

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT (COUNT(DISTINCT ?Notice) AS ?NoticeCount) WHERE {
     VALUES ?NoticePublicationDate  {
        "20230905"
    }

    ?Notice epo:hasPublicationDate ?NoticePublicationDate .

    ?Notice epo:refersToLot ?Lot .
    ?Tender epo:isSubmittedForLot ?Lot .
    ?Tender epo:foreseesSubcontracting ?Subcontrating .

}
