# We might want to see the titles (procedure titles)
# associated with some of these notices published on "20230911".
# Let's limit the results to 10 titles in English

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

SELECT ?title
WHERE {
?notice epo:hasPublicationDate "20230911" ;
epo:refersToProcedure [ epo:hasTitle ?title ] .
FILTER(LANG(?title) = 'en')
} LIMIT 10
