# Which are the values of tenders for a given day?

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cccev: <http://data.europa.eu/m8g/>

SELECT DISTINCT
?Notice
?PublicationDate
?AwardetValue
?LotAwardedValueCurrencyURI
where {

    VALUES ?PublicationDate {
        "20230911"
    }

    ?Notice epo:hasPublicationDate ?PublicationDate;
            epo:refersToLot ?Lot .
    ?LotAwardOutcome epo:describesLot ?Lot ;
                     epo:hasAwardedValue / epo:hasAmountValue ?AwardetValue;
                     epo:hasAwardedValue / epo:hasCurrency ?LotAwardedValueCurrencyURI.

}
