
@startuml
class "foaf:Agent" {
  epo:hasAlias : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  adms:identifier : adms:Identifier [0..*]
}
class "cpov:ContactPoint" {
  epo:hasContactName : rdf:PlainLiteral [0..1]
  epo:hasFax : rdf:PlainLiteral [0..*]
  cpov:telephone : rdf:PlainLiteral [0..*]
  dct:description : rdf:PlainLiteral [0..*]
  cpov:email : rdf:PlainLiteral [0..*]
  epo:hasInternetAddress : xsd:anyURI [0..1]
  locn:address : locn:Address [0..1]
}
class "epo:AgentInRole" {
  dct:description : rdf:PlainLiteral [0..*]
  dct:title : rdf:PlainLiteral [0..*]
  epo:hasContactPointInRole : cpov:ContactPoint [0..*]
  epo:playedBy : foaf:Agent [1]
  epo:contextualisedBy : epo:ProcurementObject [0..*]
  epo:exposesChannel : cv:Channel [0..*]
}
"foaf:Agent" <|-- "epo:System"
"foaf:Agent" <|-- "org:Organization"
"epo:AgentInRole" <|-- "epo:OfferingParty"
"foaf:Agent" <|-- "foaf:Person"
"epo:AgentInRole" <|-- "epo:AcquiringParty"
"epo:AgentInRole" <|-- "epo:AuxiliaryParty"
"epo-not:ResultNotice" --> "0..*" "epo:AgentInRole" : epo-not:announcesRole
"epo-not:PlanningNotice" --> "1..*" "epo:AgentInRole" : epo:announcesRole
"org:Organization" --> "0..1" "cpov:ContactPoint" : epo:hasPrimaryContactPoint
"epo:AgentInRole" --> "0..*" "cpov:ContactPoint" : epo:hasContactPointInRole
"foaf:Agent" --> "0..*" "adms:Identifier" : adms:identifier
"epo-not:CompetitionNotice" --> "1..*" "epo:AgentInRole" : epo:announcesRole
"epo:System" --> "0..1" "foaf:Agent" : epo:isOwnedByAgent
"epo:AgentInRole" --> "1" "foaf:Agent" : epo:playedBy
"epo:AgentInRole" --> "0..*" "epo:ProcurementObject" : epo:contextualisedBy
"epo-not:ResultNotice" --> "1..*" "epo:AgentInRole" : epo-not:refersToRole
"epo-not:CompletionNotice" --> "0..*" "epo:AgentInRole" : epo:refersToRole
"epo-not:CompletionNotice" --> "0..*" "epo:AgentInRole" : epo:announcesRole
"epo-not:ContractModificationNotice" --> "0..*" "epo:AgentInRole" : epo:announcesRole
"epo:AgentInRole" --> "0..*" "cv:Channel" : epo:exposesChannel
"epo:Buyer" -->  "cpov:ContactPoint" : epo:indicatesInvoiceeContactPoint
"cpov:ContactPoint" --> "0..1" "locn:Address" : locn:address
"epo-not:DirectAwardPrenotificationNotice" --> "1..*" "epo:AgentInRole" : epo:announcesRole
@enduml
